const adjectivePersonAppearanceArray = [
	{
		positive: 'anmutig',
		comparative: 'anmutiger',
		superlative: 'anmutigste',
		campaignSetting: 'Universal',
		tags: 'Anmut',
	},
	{
		positive: 'anziehend',
		comparative: 'anziehender',
		superlative: 'anziehenste',
		campaignSetting: 'Universal',
		tags: 'Anziehung',
	},
	{
		positive: 'attraktiv',
		comparative: 'attraktiver',
		superlative: 'attraktivste',
		campaignSetting: 'Universal',
		tags: 'Attraktivität',
	},
	{
		positive: 'auffällig',
		comparative: 'auffälliger',
		superlative: 'auffälligste',
		campaignSetting: 'Universal',
		tags: 'Auffälligkeit',
	},
	{
		positive: 'ausdrucksstark',
		comparative: 'ausdrucksstärker',
		superlative: 'ausdrucksstärkste',
		campaignSetting: 'Universal',
		tags: 'Ausdrucksstärke',
	},
	{
		positive: 'beeindruckend',
		comparative: 'beeindruckender',
		superlative: 'beeindruckenste',
		campaignSetting: 'Universal',
		tags: 'Eindruck',
	},
	{
		positive: 'charmant',
		comparative: 'charmanter',
		superlative: 'charmanteste',
		campaignSetting: 'Universal',
		tags: 'Charme',
	},
	{
		positive: 'elegant',
		comparative: 'eleganter',
		superlative: 'eleganteste',
		campaignSetting: 'Universal',
		tags: 'Eleganz',
	},
	{
		positive: 'gepflegt',
		comparative: 'gepflegter',
		superlative: 'gepflegteste',
		campaignSetting: 'Universal',
		tags: 'Gepflegtsein',
	},
	{
		positive: 'gutaussehend',
		comparative: 'gutaussehender',
		superlative: 'gutaussehendste',
		campaignSetting: 'Universal',
		tags: 'Gutes Aussehen',
	},
	{
		positive: 'hinreißend',
		comparative: 'hinreißender',
		superlative: 'hinreißenste',
		campaignSetting: 'Universal',
		tags: 'Hinreißung',
	},
	{
		positive: 'markant',
		comparative: 'markanter',
		superlative: 'markanteste',
		campaignSetting: 'Universal',
		tags: 'Markanz',
	},
	{
		positive: 'modisch',
		comparative: 'modischer',
		superlative: 'modischste',
		campaignSetting: 'Universal',
		tags: 'Mode',
	},
	{
		positive: 'muskulös',
		comparative: 'muskulöser',
		superlative: 'muskulöseste',
		campaignSetting: 'Universal',
		tags: 'Muskeln',
	},
	{
		positive: 'schick',
		comparative: 'schicker',
		superlative: 'schickste',
		campaignSetting: 'Universal',
		tags: 'Schick',
	},
	{
		positive: 'schlank',
		comparative: 'schlanker',
		superlative: 'schlankeste',
		campaignSetting: 'Universal',
		tags: 'Schlankheit',
	},
	{
		positive: 'selbstbewusst',
		comparative: 'selbstbewusster',
		superlative: 'selbstbewussteste',
		campaignSetting: 'Universal',
		tags: 'Selbstbewusstsein',
	},
	{
		positive: 'strahlend',
		comparative: 'strahlender',
		superlative: 'strahlendste',
		campaignSetting: 'Universal',
		tags: 'Ausstrahlung',
	},
	{
		positive: 'stylisch',
		comparative: 'stylischer',
		superlative: 'stylischste',
		campaignSetting: 'Universal',
		tags: 'Stil',
	},
	{
		positive: 'verführerisch',
		comparative: 'verführerischer',
		superlative: 'verführerrischste',
		campaignSetting: 'Universal',
		tags: 'Verführung',
	},
];
