const adjectiveCardinalDirectionArray = [
	{
		positive: 'nördlich',
		comparative: 'nördlicher',
		superlative: 'nördlichste',
		campaignSetting: 'Universal',
		tags: 'Norden',
	},
	{
		positive: 'südlich',
		comparative: 'südlicher',
		superlative: 'südlichste',
		campaignSetting: 'Universal',
		tags: 'Süden',
	},
	{
		positive: 'westlich',
		comparative: 'westlicher',
		superlative: 'westlichste',
		campaignSetting: 'Universal',
		tags: 'Westen',
	},
	{
		positive: 'östlich',
		comparative: 'östlicher',
		superlative: 'östlichste',
		campaignSetting: 'Universal',
		tags: 'Osten',
	},
	{
		positive: 'nordwestlich',
		comparative: 'nordwestlicher',
		superlative: 'nordwestlichste',
		campaignSetting: 'Universal',
		tags: 'Nordwesten',
	},
	{
		positive: 'nordöstlich',
		comparative: 'nordöstlicher',
		superlative: 'nordöstlichste',
		campaignSetting: 'Universal',
		tags: 'Nordosten',
	},
	{
		positive: 'südwestlich',
		comparative: 'südwestlicher',
		superlative: 'südwestlichste',
		campaignSetting: 'Universal',
		tags: 'Südwesten',
	},
	{
		positive: 'südöstlich',
		comparative: 'südöstlicher',
		superlative: 'südöstlichste',
		campaignSetting: 'Universal',
		tags: 'Südosten',
	},
	{
		positive: 'nordnordwestlich',
		comparative: 'nordnordwestlicher',
		superlative: 'nordnordwestlichste',
		campaignSetting: 'Universal',
		tags: 'Nordnordwesten',
	},
	{
		positive: 'nordnordöstlich',
		comparative: 'nordnordöstlicher',
		superlative: 'nordnordöstlichste',
		campaignSetting: 'Universal',
		tags: 'Nordnordosten',
	},
	{
		positive: 'südsüdwestlich',
		comparative: 'südsüdwestlicher',
		superlative: 'südsüdwestlichste',
		campaignSetting: 'Universal',
		tags: 'Südsüdwesten',
	},
	{
		positive: 'südsüdöstlich',
		comparative: 'südsüdöstlicher',
		superlative: 'südsüdöstlichste',
		campaignSetting: 'Universal',
		tags: 'Südsüdosten',
	},
	{
		positive: 'westnordwestlich',
		comparative: 'westnordwestlicher',
		superlative: 'westnordwestlichste',
		campaignSetting: 'Universal',
		tags: 'Westnordwesten',
	},
	{
		positive: 'ostnordöstlich',
		comparative: 'ostnordöstlicher',
		superlative: 'ostnordöstlichste',
		campaignSetting: 'Universal',
		tags: 'Ostnordosten',
	},
	{
		positive: 'westsüdwestlich',
		comparative: 'westsüdwestlicher',
		superlative: 'westsüdwestlichste',
		campaignSetting: 'Universal',
		tags: 'Westsüdwesten',
	},
	{
		positive: 'ostsüdöstlich',
		comparative: 'ostsüdöstlicher',
		superlative: 'ostsüdöstlichste',
		campaignSetting: 'Universal',
		tags: 'Ostsüdosten',
	},
	{
		positive: 'nordwestsüdwestlich',
		comparative: 'nordwestsüdwestlicher',
		superlative: 'nordwestsüdwestlichste',
		campaignSetting: 'Universal',
		tags: 'Nordwestsüdwesten',
	},
	{
		positive: 'nordostsüdöstlich',
		comparative: 'nordostsüdöstlicher',
		superlative: 'nordostsüdöstlichste',
		campaignSetting: 'Universal',
		tags: 'Nordostsüdosten',
	},
	{
		positive: 'südwestnordwestlich',
		comparative: 'südwestnordwestlicher',
		superlative: 'südwestnordwestlichste',
		campaignSetting: 'Universal',
		tags: 'Südwestnordwest',
	},
	{
		positive: 'südostnordöstlich',
		comparative: 'südostnordöstlicher',
		superlative: 'südostnordöstlichste',
		campaignSetting: 'Universal',
		tags: 'Südostnordosten',
	},
];
