const adventuringGearArray = [
	{
		singular: 'Abakus',
		plural: 'Abakusse',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Abakusse',
	},
	{
		singular: 'Laterne',
		plural: 'Laternen',
		adjective: 'abdeckbare',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Abdeckbare Laternen',
	},
	{
		singular: 'Amulett',
		plural: 'Amulette',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Amulette',
	},
	{
		singular: 'Angelausrüstung',
		plural: 'Angelausrüstungen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Angelausrüstungen',
	},
	{
		singular: 'Armbrustbolzen',
		plural: 'Armbrustbolzen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Armbrustbolzen',
	},
	{
		singular: 'Armbrustbolzenbehälter',
		plural: 'Armbrustbolzenbehälter',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Armbrustbolzenbehälter',
	},
	{
		singular: 'Blasrohrpfeile',
		plural: 'Blasrohrpfeile',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Blasrohrpfeile',
	},
	{
		singular: 'Blatt',
		plural: 'Blätter',
		adjective: '',
		prefix: '',
		suffix: 'Papier',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Blätter Papier',
	},
	{
		singular: 'Blendlaterne',
		plural: 'Blendlaternen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Blendlaternen',
	},
	{
		singular: 'Brechstange',
		plural: 'Brechstangen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Brechstangen',
	},
	{
		singular: 'Buch',
		plural: 'Bücher',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'gemischteDeklination',
		declinationPattern: 'W3',
		campaignSetting: 'Universal',
		tags: 'Bücher',
	},
	{
		singular: 'Decke',
		plural: 'Decken',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Decken',
	},
	{
		singular: 'Drei-Schritt-Stange',
		plural: 'Drei-Schritt-Stangen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Drei-Schritt-Stangen',
	},
	{
		singular: 'Eibenzauberstab',
		plural: 'Eibenzauberstäbe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Eibenzauberstäbe',
	},
	{
		singular: 'Eimer',
		plural: 'Eimer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Eimer',
	},
	{
		singular: 'Eisenkeile',
		plural: 'Eisenkeile',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Eisenkeile',
	},
	{
		singular: 'Eisentopf',
		plural: 'Eisentöpfe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Eisentöpfe',
	},
	{
		singular: 'Emblem',
		plural: 'Embleme',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Embleme',
	},
	{
		singular: 'Enterhaken',
		plural: 'Enterhaken',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Enterhaken',
	},
	{
		singular: 'Fackel',
		plural: 'Fackeln',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Fackeln',
	},
	{
		singular: 'Fangeisen',
		plural: 'Fangeisen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Fangeisen',
	},
	{
		singular: 'Fass',
		plural: 'Fässer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Fässer',
	},
	{
		singular: 'Kleidung',
		plural: 'Kleidungen',
		adjective: 'feine',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Feine Kleidungen',
	},
	{
		singular: 'Fernglas',
		plural: 'Ferngläser',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Ferngläser',
	},
	{
		singular: 'Tintenfläschchen',
		plural: 'Tintenfläschchen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Tintenfläschchen',
	},
	{
		singular: 'Alchemistenfeuerflasche',
		plural: 'Alchemistenfeuerflaschen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Alchemistenfeuerflaschen',
	},
	{
		singular: 'Ölflasche',
		plural: 'Ölflaschen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Ölflaschen',
	},
	{
		singular: 'Flaschenzug',
		plural: 'Flaschenzüge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Flaschenzüge',
	},
	{
		singular: 'Gegengiftphiole',
		plural: 'Gegengiftphiolen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Gegengiftphiolen',
	},
	{
		singular: 'Kleidung',
		plural: 'Kleidungen',
		adjective: 'gewöhnliche',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Gewöhnliche Kleidungen',
	},
	{
		singular: 'Giftphiole',
		plural: 'Giftphiolen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Giftphiolen',
	},
	{
		singular: 'Glasflasche',
		plural: 'Glasflaschen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Glasflaschen',
	},
	{
		singular: 'Glocke',
		plural: 'Glocken',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Glocken',
	},
	{
		singular: 'Hammer',
		plural: 'Hämmer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Hämmer',
	},
	{
		singular: 'Handschellen',
		plural: 'Handschellen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Handschellen',
	},
	{
		singular: 'Hanfseil',
		plural: 'Hanfseile',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Hanfseile',
	},
	{
		singular: 'Heilerausrüstung',
		plural: 'Heilerausrüstungen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Heilerausrüstungen',
	},
	{
		singular: 'Heiltrank',
		plural: 'Heiltränke',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Heiltränke',
	},
	{
		singular: 'Holzstab',
		plural: 'Holzstäbe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Holzstäbe',
	},
	{
		singular: 'Kaufmannswaage',
		plural: 'Kaufmannswaagen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kaufmannswaagen',
	},
	{
		singular: 'Kerze',
		plural: 'Kerzen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kerzen',
	},
	{
		singular: 'Kette',
		plural: 'Ketten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Ketten',
	},
	{
		singular: 'Kiste',
		plural: 'Kisten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kisten',
	},
	{
		singular: 'Kletterausrüstung',
		plural: 'Kletterausrüstungen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kletterausrüstungen',
	},
	{
		singular: 'Kletterhaken',
		plural: 'Kletterhaken',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kletterhaken',
	},
	{
		singular: 'Köcher',
		plural: 'Köcher',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Köcher',
	},
	{
		singular: 'Korb',
		plural: 'Körbe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Körbe',
	},
	{
		singular: 'Kostüm',
		plural: 'Kostüme',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S5',
		campaignSetting: 'Universal',
		tags: 'Kostüme',
	},
	{
		singular: 'Krähenfuß',
		plural: 'Krähenfüße',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Krähenfüße',
	},
	{
		singular: 'Kreide',
		plural: 'Kreiden',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kreiden',
	},
	{
		singular: 'Kristall',
		plural: 'Kristalle',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kristalle',
	},
	{
		singular: 'Kugel',
		plural: 'Kugeln',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kugeln',
	},
	{
		singular: 'Lampe',
		plural: 'Lampen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Lampen',
	},
	{
		singular: 'Leiter',
		plural: 'Leitern',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Leitern',
	},
	{
		singular: 'Materialkomponentenbeutel',
		plural: 'Materialkomponentenbeutel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Materialkomponentenbeutel',
	},
	{
		singular: 'Metallkügelchen',
		plural: 'Metallkügelchen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Metallkügelchen',
	},
	{
		singular: 'Mistelzweigsprößling',
		plural: 'Mistelzweigsprößlinge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Mistelzweigsprößlinge',
	},
	{
		singular: 'Blatt',
		plural: 'Blätter',
		adjective: '',
		prefix: '',
		suffix: 'Pergament',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Blätter Pergament',
	},
	{
		singular: 'Pfeil',
		plural: 'Pfeile',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Pfeile',
	},
	{
		singular: 'Phiole',
		plural: 'Phiolen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Phiolen',
	},
	{
		singular: 'Parfümphiole',
		plural: 'Parfümphiolen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Parfümphiolen',
	},
	{
		singular: 'Säurephiole',
		plural: 'Säurephiolen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Säurephiolen',
	},
	{
		singular: 'Reisegeschirr',
		plural: 'Reisegeschirre',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Reisegeschirre',
	},
	{
		singular: 'Reisekleidung',
		plural: 'Reisekleidungen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Reisekleidungen',
	},
	{
		singular: 'Reliquie',
		plural: 'Reliquien',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Reliquien',
	},
	{
		singular: 'Robe',
		plural: 'Roben',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Roben',
	},
	{
		singular: 'Rucksack',
		plural: 'Rucksäcke',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Rucksäcke',
	},
	{
		singular: 'Rute',
		plural: 'Ruten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Ruten',
	},
	{
		singular: 'Sack',
		plural: 'Säcke',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Säcke',
	},
	{
		singular: 'Sanduhr',
		plural: 'Sanduhren',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Sanduhren',
	},
	{
		singular: 'Schaufel',
		plural: 'Schaufeln',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Schaufeln',
	},
	{
		singular: 'Schlafsack',
		plural: 'Schlafsäcke',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Schlafsäcke',
	},
	{
		singular: 'Schleuderkugel',
		plural: 'Schleuderkugeln',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Schleuderkugeln',
	},
	{
		singular: 'Schloss',
		plural: 'Schlösser',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Schlösser',
	},
	{
		singular: 'Schneeschuh',
		plural: 'Schneeschuhe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Schneeschuhe',
	},
	{
		singular: 'Schreibfeder',
		plural: 'Schreibfedern',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Schreibfedern',
	},
	{
		singular: 'Schriftrollenbehälter',
		plural: 'Schriftrollenbehälter',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schriftrollenbehälter',
	},
	{
		singular: 'Seidenseil',
		plural: 'Seidenseile',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Seidenseile',
	},
	{
		singular: 'Seife',
		plural: 'Seifen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Seifen',
	},
	{
		singular: 'Siegelring',
		plural: 'Siegelringe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Siegelringe',
	},
	{
		singular: 'Siegelwachs',
		plural: 'Siegelwachse',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Siegelwachse',
	},
	{
		singular: 'Signalpfeife',
		plural: 'Signalpfeifen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Signalpfeifen',
	},
	{
		singular: 'Spitzhacke',
		plural: 'Spitzhacken',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Spitzhacken',
	},
	{
		singular: 'Stab',
		plural: 'Stäbe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Stäbe',
	},
	{
		singular: 'Stahlspiegel',
		plural: 'Stahlspiegel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Stahlspiegel',
	},
	{
		singular: 'Tagesration',
		plural: 'Tagesrationen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Tagesrationen',
	},
	{
		singular: 'Tasche',
		plural: 'Taschen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Taschen',
	},
	{
		singular: 'Tonhumpen',
		plural: 'Tonhumpen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Tonhumpen',
	},
	{
		singular: 'Tonkrug',
		plural: 'Tonkrüge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Tonkrüge',
	},
	{
		singular: 'Totem',
		plural: 'Totems',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Totems',
	},
	{
		singular: 'Rammbock',
		plural: 'Rammböcke',
		adjective: 'tragbare',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Tragbare Rammböcke',
	},
	{
		singular: 'Trinkschlauch',
		plural: 'Trinkschläuche',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Trinkschläuche',
	},
	{
		singular: 'Vergrößerungsglas',
		plural: 'Vergrößerungsgläser',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Vergrößerungsgläser',
	},
	{
		singular: 'Vorschlaghammer',
		plural: 'Vorschlaghämmer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Vorschlaghämmer',
	},
	{
		singular: 'Weihwasser',
		plural: 'Weihwässer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Weihwässer',
	},
	{
		singular: 'Wetzstein',
		plural: 'Wetzsteine',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Wetzsteine',
	},
	{
		singular: 'Zauberbuch',
		plural: 'Zauberbücher',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Zauberbücher',
	},
	{
		singular: 'Zauberstab',
		plural: 'Zauberstäbe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Zauberstäbe',
	},
	{
		singular: 'Zelt',
		plural: 'Zelte',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Zelte',
	},
	{
		singular: 'Zunderkästchen',
		plural: 'Zunderkästchen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Zunderkästchen',
	},
];
