const adventuringGearArray = [
	{
		nounSingular: 'Abakus',
		nounPlural: 'Abakusse',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Abakusse',
	},
	{
		nounSingular: 'Laterne',
		nounPlural: 'Laternen',
		nounAdjective: 'abdeckbare',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Abdeckbare Laternen',
	},
	{
		nounSingular: 'Amulett',
		nounPlural: 'Amulette',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Amulette',
	},
	{
		nounSingular: 'Angelausrüstung',
		nounPlural: 'Angelausrüstungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Angelausrüstungen',
	},
	{
		nounSingular: 'Armbrustbolzen',
		nounPlural: 'Armbrustbolzen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Armbrustbolzen',
	},
	{
		nounSingular: 'Armbrustbolzenbehälter',
		nounPlural: 'Armbrustbolzenbehälter',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Armbrustbolzenbehälter',
	},
	{
		nounSingular: 'Blasrohrpfeile',
		nounPlural: 'Blasrohrpfeile',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Blasrohrpfeile',
	},
	{
		nounSingular: 'Blatt',
		nounPlural: 'Blätter',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: 'Papier',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Blätter Papier',
	},
	{
		nounSingular: 'Blendlaterne',
		nounPlural: 'Blendlaternen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Blendlaternen',
	},
	{
		nounSingular: 'Brechstange',
		nounPlural: 'Brechstangen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Brechstangen',
	},
	{
		nounSingular: 'Buch',
		nounPlural: 'Bücher',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'gemischteDeklination',
		declinationPattern: 'W3',
		campaignSetting: 'Universal',
		tags: 'Bücher',
	},
	{
		nounSingular: 'Decke',
		nounPlural: 'Decken',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Decken',
	},
	{
		nounSingular: 'Drei-Schritt-Stange',
		nounPlural: 'Drei-Schritt-Stangen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Drei-Schritt-Stangen',
	},
	{
		nounSingular: 'Eibenzauberstab',
		nounPlural: 'Eibenzauberstäbe',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Eibenzauberstäbe',
	},
	{
		nounSingular: 'Eimer',
		nounPlural: 'Eimer',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Eimer',
	},
	{
		nounSingular: 'Eisenkeile',
		nounPlural: 'Eisenkeile',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Eisenkeile',
	},
	{
		nounSingular: 'Eisentopf',
		nounPlural: 'Eisentöpfe',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Eisentöpfe',
	},
	{
		nounSingular: 'Emblem',
		nounPlural: 'Embleme',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Embleme',
	},
	{
		nounSingular: 'Enterhaken',
		nounPlural: 'Enterhaken',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Enterhaken',
	},
	{
		nounSingular: 'Fackel',
		nounPlural: 'Fackeln',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Fackeln',
	},
	{
		nounSingular: 'Fangeisen',
		nounPlural: 'Fangeisen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Fangeisen',
	},
	{
		nounSingular: 'Fass',
		nounPlural: 'Fässer',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Fässer',
	},
	{
		nounSingular: 'Kleidung',
		nounPlural: 'Kleidungen',
		nounAdjective: 'feine',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Feine Kleidungen',
	},
	{
		nounSingular: 'Fernglas',
		nounPlural: 'Ferngläser',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Ferngläser',
	},
	{
		nounSingular: 'Tintenfläschchen',
		nounPlural: 'Tintenfläschchen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Tintenfläschchen',
	},
	{
		nounSingular: 'Alchemistenfeuerflasche',
		nounPlural: 'Alchemistenfeuerflaschen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Alchemistenfeuerflaschen',
	},
	{
		nounSingular: 'Ölflasche',
		nounPlural: 'Ölflaschen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Ölflaschen',
	},
	{
		nounSingular: 'Flaschenzug',
		nounPlural: 'Flaschenzüge',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Flaschenzüge',
	},
	{
		nounSingular: 'Gegengiftphiole',
		nounPlural: 'Gegengiftphiolen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Gegengiftphiolen',
	},
	{
		nounSingular: 'Kleidung',
		nounPlural: 'Kleidungen',
		nounAdjective: 'gewöhnliche',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Gewöhnliche Kleidungen',
	},
	{
		nounSingular: 'Giftphiole',
		nounPlural: 'Giftphiolen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Giftphiolen',
	},
	{
		nounSingular: 'Glasflasche',
		nounPlural: 'Glasflaschen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Glasflaschen',
	},
	{
		nounSingular: 'Glocke',
		nounPlural: 'Glocken',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Glocken',
	},
	{
		nounSingular: 'Hammer',
		nounPlural: 'Hämmer',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Hämmer',
	},
	{
		nounSingular: 'Handschellen',
		nounPlural: 'Handschellen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Handschellen',
	},
	{
		nounSingular: 'Hanfseil',
		nounPlural: 'Hanfseile',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Hanfseile',
	},
	{
		nounSingular: 'Heilerausrüstung',
		nounPlural: 'Heilerausrüstungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Heilerausrüstungen',
	},
	{
		nounSingular: 'Heiltrank',
		nounPlural: 'Heiltränke',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Heiltränke',
	},
	{
		nounSingular: 'Holzstab',
		nounPlural: 'Holzstäbe',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Holzstäbe',
	},
	{
		nounSingular: 'Kaufmannswaage',
		nounPlural: 'Kaufmannswaagen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kaufmannswaagen',
	},
	{
		nounSingular: 'Kerze',
		nounPlural: 'Kerzen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kerzen',
	},
	{
		nounSingular: 'Kette',
		nounPlural: 'Ketten',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Ketten',
	},
	{
		nounSingular: 'Kiste',
		nounPlural: 'Kisten',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kisten',
	},
	{
		nounSingular: 'Kletterausrüstung',
		nounPlural: 'Kletterausrüstungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kletterausrüstungen',
	},
	{
		nounSingular: 'Kletterhaken',
		nounPlural: 'Kletterhaken',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kletterhaken',
	},
	{
		nounSingular: 'Köcher',
		nounPlural: 'Köcher',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Köcher',
	},
	{
		nounSingular: 'Korb',
		nounPlural: 'Körbe',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Körbe',
	},
	{
		nounSingular: 'Kostüm',
		nounPlural: 'Kostüme',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S5',
		campaignSetting: 'Universal',
		tags: 'Kostüme',
	},
	{
		nounSingular: 'Krähenfuß',
		nounPlural: 'Krähenfüße',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Krähenfüße',
	},
	{
		nounSingular: 'Kreide',
		nounPlural: 'Kreiden',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kreiden',
	},
	{
		nounSingular: 'Kristall',
		nounPlural: 'Kristalle',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kristalle',
	},
	{
		nounSingular: 'Kugel',
		nounPlural: 'Kugeln',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kugeln',
	},
	{
		nounSingular: 'Lampe',
		nounPlural: 'Lampen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Lampen',
	},
	{
		nounSingular: 'Leiter',
		nounPlural: 'Leitern',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Leitern',
	},
	{
		nounSingular: 'Materialkomponentenbeutel',
		nounPlural: 'Materialkomponentenbeutel',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Materialkomponentenbeutel',
	},
	{
		nounSingular: 'Metallkügelchen',
		nounPlural: 'Metallkügelchen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Metallkügelchen',
	},
	{
		nounSingular: 'Mistelzweigsprößling',
		nounPlural: 'Mistelzweigsprößlinge',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Mistelzweigsprößlinge',
	},
	{
		nounSingular: 'Blatt',
		nounPlural: 'Blätter',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: 'Pergament',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Blätter Pergament',
	},
	{
		nounSingular: 'Pfeil',
		nounPlural: 'Pfeile',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Pfeile',
	},
	{
		nounSingular: 'Phiole',
		nounPlural: 'Phiolen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Phiolen',
	},
	{
		nounSingular: 'Parfümphiole',
		nounPlural: 'Parfümphiolen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Parfümphiolen',
	},
	{
		nounSingular: 'Säurephiole',
		nounPlural: 'Säurephiolen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Säurephiolen',
	},
	{
		nounSingular: 'Reisegeschirr',
		nounPlural: 'Reisegeschirre',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Reisegeschirre',
	},
	{
		nounSingular: 'Reisekleidung',
		nounPlural: 'Reisekleidungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Reisekleidungen',
	},
	{
		nounSingular: 'Reliquie',
		nounPlural: 'Reliquien',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Reliquien',
	},
	{
		nounSingular: 'Robe',
		nounPlural: 'Roben',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Roben',
	},
	{
		nounSingular: 'Rucksack',
		nounPlural: 'Rucksäcke',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Rucksäcke',
	},
	{
		nounSingular: 'Rute',
		nounPlural: 'Ruten',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Ruten',
	},
	{
		nounSingular: 'Sack',
		nounPlural: 'Säcke',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Säcke',
	},
	{
		nounSingular: 'Sanduhr',
		nounPlural: 'Sanduhren',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Sanduhren',
	},
	{
		nounSingular: 'Schaufel',
		nounPlural: 'Schaufeln',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Schaufeln',
	},
	{
		nounSingular: 'Schlafsack',
		nounPlural: 'Schlafsäcke',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Schlafsäcke',
	},
	{
		nounSingular: 'Schleuderkugel',
		nounPlural: 'Schleuderkugeln',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Schleuderkugeln',
	},
	{
		nounSingular: 'Schloss',
		nounPlural: 'Schlösser',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Schlösser',
	},
	{
		nounSingular: 'Schneeschuh',
		nounPlural: 'Schneeschuhe',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Schneeschuhe',
	},
	{
		nounSingular: 'Schreibfeder',
		nounPlural: 'Schreibfedern',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Schreibfedern',
	},
	{
		nounSingular: 'Schriftrollenbehälter',
		nounPlural: 'Schriftrollenbehälter',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schriftrollenbehälter',
	},
	{
		nounSingular: 'Seidenseil',
		nounPlural: 'Seidenseile',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Seidenseile',
	},
	{
		nounSingular: 'Seife',
		nounPlural: 'Seifen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Seifen',
	},
	{
		nounSingular: 'Siegelring',
		nounPlural: 'Siegelringe',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Siegelringe',
	},
	{
		nounSingular: 'Siegelwachs',
		nounPlural: 'Siegelwachse',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Siegelwachse',
	},
	{
		nounSingular: 'Signalpfeife',
		nounPlural: 'Signalpfeifen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Signalpfeifen',
	},
	{
		nounSingular: 'Spitzhacke',
		nounPlural: 'Spitzhacken',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Spitzhacken',
	},
	{
		nounSingular: 'Stab',
		nounPlural: 'Stäbe',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Stäbe',
	},
	{
		nounSingular: 'Stahlspiegel',
		nounPlural: 'Stahlspiegel',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Stahlspiegel',
	},
	{
		nounSingular: 'Tagesration',
		nounPlural: 'Tagesrationen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Tagesrationen',
	},
	{
		nounSingular: 'Tasche',
		nounPlural: 'Taschen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Taschen',
	},
	{
		nounSingular: 'Tonhumpen',
		nounPlural: 'Tonhumpen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Tonhumpen',
	},
	{
		nounSingular: 'Tonkrug',
		nounPlural: 'Tonkrüge',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Tonkrüge',
	},
	{
		nounSingular: 'Totem',
		nounPlural: 'Totems',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Totems',
	},
	{
		nounSingular: 'Rammbock',
		nounPlural: 'Rammböcke',
		nounAdjective: 'tragbare',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Tragbare Rammböcke',
	},
	{
		nounSingular: 'Trinkschlauch',
		nounPlural: 'Trinkschläuche',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Trinkschläuche',
	},
	{
		nounSingular: 'Vergrößerungsglas',
		nounPlural: 'Vergrößerungsgläser',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Vergrößerungsgläser',
	},
	{
		nounSingular: 'Vorschlaghammer',
		nounPlural: 'Vorschlaghämmer',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Vorschlaghämmer',
	},
	{
		nounSingular: 'Weihwasser',
		nounPlural: 'Weihwässer',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Weihwässer',
	},
	{
		nounSingular: 'Wetzstein',
		nounPlural: 'Wetzsteine',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Wetzsteine',
	},
	{
		nounSingular: 'Zauberbuch',
		nounPlural: 'Zauberbücher',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Zauberbücher',
	},
	{
		nounSingular: 'Zauberstab',
		nounPlural: 'Zauberstäbe',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Zauberstäbe',
	},
	{
		nounSingular: 'Zelt',
		nounPlural: 'Zelte',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Zelte',
	},
	{
		nounSingular: 'Zunderkästchen',
		nounPlural: 'Zunderkästchen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Zunderkästchen',
	},
];
