const animalArray = [
	{
		nounSingular: 'Bär',
		nounPlural: 'Bären',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Bären',
	},
	{
		nounSingular: 'Käfer',
		nounPlural: 'Käfer',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Insekten,Käfer',
	},
	{
		nounSingular: 'Katze',
		nounPlural: 'Katzen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Katzen',
	},
	{
		nounSingular: 'Reh',
		nounPlural: 'Rehe',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Rehe',
	},
	{
		nounSingular: 'Hund',
		nounPlural: 'Hunde',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Hunde',
	},
	{
		nounSingular: 'Delphin',
		nounPlural: 'Delphine',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Delphine',
	},
	{
		nounSingular: 'Esel',
		nounPlural: 'Esel',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Esel',
	},
	{
		nounSingular: 'Adler',
		nounPlural: 'Adler',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Vögel,Adler',
	},
	{
		nounSingular: 'Frosch',
		nounPlural: 'Frösche',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Amphibien,Frösche',
	},
	{
		nounSingular: 'Löwe',
		nounPlural: 'Löwen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Löwen',
	},
	{
		nounSingular: 'Echse',
		nounPlural: 'Echsen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Reptilien,Echsen',
	},
	{
		nounSingular: 'Orang-Utan',
		nounPlural: 'Orang-Utans',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Orang-Utans',
	},
	{
		nounSingular: 'Otter',
		nounPlural: 'Otter',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Otter',
	},
	{
		nounSingular: 'Schwein',
		nounPlural: 'Schweine',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Schweine',
	},
	{
		nounSingular: 'Hase',
		nounPlural: 'Hasen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Hasen',
	},
	{
		nounSingular: 'Rabe',
		nounPlural: 'Raben',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Vögel,Raben',
	},
	{
		nounSingular: 'Lachs',
		nounPlural: 'Lachse',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Fische,Lachse',
	},
	{
		nounSingular: 'Tiger',
		nounPlural: 'Tiger',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Tiger',
	},
	{
		nounSingular: 'Wal',
		nounPlural: 'Wale',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Wale',
	},
	{
		nounSingular: 'Wolf',
		nounPlural: 'Wölfe',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Wölfe',
	},
];
