const animalArray = [
	{
		singular: 'Bär',
		plural: 'Bären',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Bären',
	},
	{
		singular: 'Käfer',
		plural: 'Käfer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Insekten,Käfer',
	},
	{
		singular: 'Katze',
		plural: 'Katzen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Katzen',
	},
	{
		singular: 'Reh',
		plural: 'Rehe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Rehe',
	},
	{
		singular: 'Hund',
		plural: 'Hunde',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Hunde',
	},
	{
		singular: 'Delphin',
		plural: 'Delphine',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Delphine',
	},
	{
		singular: 'Esel',
		plural: 'Esel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Esel',
	},
	{
		singular: 'Adler',
		plural: 'Adler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Vögel,Adler',
	},
	{
		singular: 'Frosch',
		plural: 'Frösche',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Amphibien,Frösche',
	},
	{
		singular: 'Löwe',
		plural: 'Löwen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Löwen',
	},
	{
		singular: 'Echse',
		plural: 'Echsen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Reptilien,Echsen',
	},
	{
		singular: 'Orang-Utan',
		plural: 'Orang-Utans',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Orang-Utans',
	},
	{
		singular: 'Otter',
		plural: 'Otter',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Otter',
	},
	{
		singular: 'Schwein',
		plural: 'Schweine',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Schweine',
	},
	{
		singular: 'Hase',
		plural: 'Hasen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Hasen',
	},
	{
		singular: 'Rabe',
		plural: 'Raben',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Vögel,Raben',
	},
	{
		singular: 'Lachs',
		plural: 'Lachse',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Fische,Lachse',
	},
	{
		singular: 'Tiger',
		plural: 'Tiger',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Tiger',
	},
	{
		singular: 'Wal',
		plural: 'Wale',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Wale',
	},
	{
		singular: 'Wolf',
		plural: 'Wölfe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Säugetiere,Wölfe',
	},
];
