const armourArray = [
	{
		singular: 'Brustplatte',
		plural: 'Brustplatten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Schwere Rüstungen,Brustplatten',
	},
	{
		singular: 'Fellrüstung',
		plural: 'Fellrüstungen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Mittelschwere Rüstungen,Fellrüstungen',
	},
	{
		singular: 'Rüstung',
		plural: 'Rüstungen',
		adjective: 'gefütterte',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Leichte Rüstungen,Gefütterte Rüstungen',
	},
	{
		singular: 'Kettenhemd',
		plural: 'Kettenhemden',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'gemischteDeklination',
		declinationPattern: 'W3',
		campaignSetting: 'Universal',
		tags: 'Mittelschwere Rüstungen,Kettenhemden',
	},
	{
		singular: 'Kettenpanzer',
		plural: 'Kettenpanzer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schwere Rüstungen,Kettenpanzer',
	},
	{
		singular: 'Lederrüstung',
		plural: 'Lederrüstungen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Mittelschwere Rüstungen,Lederrüstungen',
	},
	{
		singular: 'Plattenpanzer',
		plural: 'Plattenpanzer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schwere Rüstungen,Plattenpanzer',
	},
	{
		singular: 'Schienenpanzer',
		plural: 'Schienenpanzer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schwere Rüstungen,Schienenpanzer',
	},
	{
		singular: 'Schuppenpanzer',
		plural: 'Schuppenpanzer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Mittelschwere Rüstungen,Schuppenpanzer',
	},
];
