const buildingArray = [
	{
		singular: 'Apotheke',
		plural: 'Apotheken',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Apotheken',
	},
	{
		singular: 'Schießstand',
		plural: 'Schießstände',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Schießstände',
	},
	{
		singular: 'Arena',
		plural: 'Arenen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Arenen',
	},
	{
		singular: 'Waffenkammer',
		plural: 'Waffenkammern',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Waffenkammern',
	},
	{
		singular: 'Bank',
		plural: 'Bänke',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Bänke',
	},
	{
		singular: 'Kaserne',
		plural: 'Kasernen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kasernen',
	},
	{
		singular: 'Uhrenturm',
		plural: 'Uhrentürme',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Uhrentürme',
	},
	{
		singular: 'Gießerei',
		plural: 'Gießereien',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Gießereien',
	},
	{
		singular: 'Torhaus',
		plural: 'Torhäuser',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Torhäuser',
	},
	{
		singular: 'Haus',
		plural: 'Häuser',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Häuser',
	},
	{
		singular: 'Kerker',
		plural: 'Kerker',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kerker',
	},
	{
		singular: 'Mühle',
		plural: 'Mühlen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Mühlen',
	},
	{
		singular: 'Münzstätte',
		plural: 'Münzstätten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Münzstätten',
	},
	{
		singular: 'Ruine',
		plural: 'Ruinen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Ruinen',
	},
	{
		singular: 'Laden',
		plural: 'Läden',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S5',
		campaignSetting: 'Universal',
		tags: 'Läden',
	},
	{
		singular: 'Pferdestall',
		plural: 'Pferdeställe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Pferdeställe',
	},
	{
		singular: 'Taverne',
		plural: 'Tavernen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Tavernen',
	},
	{
		singular: 'Tempel',
		plural: 'Tempel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Tempel',
	},
	{
		singular: 'Theater',
		plural: 'Theater',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Theater',
	},
	{
		singular: 'Universität',
		plural: 'Universitäten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Universitäten',
	},
];

// const buildingArray = [
// 	{
// 		singular: 'Apotheke',
// 		plural: 'Apotheken',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Apotheken',
// 	},
// 	{
// 		singular: 'Schießstand',
// 		plural: 'Schießstände',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'maskulinum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S1',
// 		campaignSetting: 'Universal',
// 		tags: 'Schießstände',
// 	},
// 	{
// 		singular: 'Arena',
// 		plural: 'Arenen',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Arenen',
// 	},
// 	{
// 		singular: 'Waffenkammer',
// 		plural: 'Waffenkammern',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Waffenkammern',
// 	},
// 	{
// 		singular: 'Bank',
// 		plural: 'Bänke',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'S3',
// 		campaignSetting: 'Universal',
// 		tags: 'Bänke',
// 	},
// 	{
// 		singular: 'Kaserne',
// 		plural: 'Kasernen',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Kasernen',
// 	},
// 	{
// 		singular: 'Uhrenturm',
// 		plural: 'Uhrentürme',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'maskulinum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S1',
// 		campaignSetting: 'Universal',
// 		tags: 'Uhrentürme',
// 	},
// 	{
// 		singular: 'Gießerei',
// 		plural: 'Gießereien',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Gießereien',
// 	},
// 	{
// 		singular: 'Torhaus',
// 		plural: 'Torhäuser',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'neutrum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S2',
// 		campaignSetting: 'Universal',
// 		tags: 'Torhäuser',
// 	},
// 	{
// 		singular: 'Haus',
// 		plural: 'Häuser',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'neutrum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S2',
// 		campaignSetting: 'Universal',
// 		tags: 'Häuser',
// 	},
// 	{
// 		singular: 'Kerker',
// 		plural: 'Kerker',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'maskulinum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S6',
// 		campaignSetting: 'Universal',
// 		tags: 'Kerker',
// 	},
// 	{
// 		singular: 'Mühle',
// 		plural: 'Mühlen',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Mühlen',
// 	},
// 	{
// 		singular: 'Münzstätte',
// 		plural: 'Münzstätten',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Münzstätten',
// 	},
// 	{
// 		singular: 'Ruine',
// 		plural: 'Ruinen',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Ruinen',
// 	},
// 	{
// 		singular: 'Laden',
// 		plural: 'Läden',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'maskulinum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S5',
// 		campaignSetting: 'Universal',
// 		tags: 'Läden',
// 	},
// 	{
// 		singular: 'Pferdestall',
// 		plural: 'Pferdeställe',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'maskulinum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S1',
// 		campaignSetting: 'Universal',
// 		tags: 'Pferdeställe',
// 	},
// 	{
// 		singular: 'Taverne',
// 		plural: 'Tavernen',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Tavernen',
// 	},
// 	{
// 		singular: 'Tempel',
// 		plural: 'Tempel',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'maskulinum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S6',
// 		campaignSetting: 'Universal',
// 		tags: 'Tempel',
// 	},
// 	{
// 		singular: 'Theater',
// 		plural: 'Theater',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'neutrum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S6',
// 		campaignSetting: 'Universal',
// 		tags: 'Theater',
// 	},
// 	{
// 		singular: 'Universität',
// 		plural: 'Universitäten',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		gender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Universitäten',
// 	},
// ];
