const buildingArray = [
	{
		nounSingular: 'Apotheke',
		nounPlural: 'Apotheken',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Apotheken',
	},
	{
		nounSingular: 'Schießstand',
		nounPlural: 'Schießstände',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Schießstände',
	},
	{
		nounSingular: 'Arena',
		nounPlural: 'Arenen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Arenen',
	},
	{
		nounSingular: 'Waffenkammer',
		nounPlural: 'Waffenkammern',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Waffenkammern',
	},
	{
		nounSingular: 'Bank',
		nounPlural: 'Bänke',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'S3',
		campaignSetting: 'Universal',
		tags: 'Bänke',
	},
	{
		nounSingular: 'Kaserne',
		nounPlural: 'Kasernen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kasernen',
	},
	{
		nounSingular: 'Uhrenturm',
		nounPlural: 'Uhrentürme',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Uhrentürme',
	},
	{
		nounSingular: 'Gießerei',
		nounPlural: 'Gießereien',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Gießereien',
	},
	{
		nounSingular: 'Torhaus',
		nounPlural: 'Torhäuser',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Torhäuser',
	},
	{
		nounSingular: 'Haus',
		nounPlural: 'Häuser',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Häuser',
	},
	{
		nounSingular: 'Kerker',
		nounPlural: 'Kerker',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kerker',
	},
	{
		nounSingular: 'Mühle',
		nounPlural: 'Mühlen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Mühlen',
	},
	{
		nounSingular: 'Münzstätte',
		nounPlural: 'Münzstätten',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Münzstätten',
	},
	{
		nounSingular: 'Ruine',
		nounPlural: 'Ruinen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Ruinen',
	},
	{
		nounSingular: 'Laden',
		nounPlural: 'Läden',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S5',
		campaignSetting: 'Universal',
		tags: 'Läden',
	},
	{
		nounSingular: 'Pferdestall',
		nounPlural: 'Pferdeställe',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Pferdeställe',
	},
	{
		nounSingular: 'Taverne',
		nounPlural: 'Tavernen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Tavernen',
	},
	{
		nounSingular: 'Tempel',
		nounPlural: 'Tempel',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Tempel',
	},
	{
		nounSingular: 'Theater',
		nounPlural: 'Theater',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Theater',
	},
	{
		nounSingular: 'Universität',
		nounPlural: 'Universitäten',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Universitäten',
	},
];
