const buildingArray = [
	{
		nounSingular: 'Apotheke',
		nounPlural: 'Apotheken',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Apotheken',
	},
	{
		nounSingular: 'Schießstand',
		nounPlural: 'Schießstände',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Schießstände',
	},
	{
		nounSingular: 'Arena',
		nounPlural: 'Arenen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Arenen',
	},
	{
		nounSingular: 'Waffenkammer',
		nounPlural: 'Waffenkammern',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Waffenkammern',
	},
	{
		nounSingular: 'Bank',
		nounPlural: 'Bänke',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Bänke',
	},
	{
		nounSingular: 'Kaserne',
		nounPlural: 'Kasernen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kasernen',
	},
	{
		nounSingular: 'Uhrenturm',
		nounPlural: 'Uhrentürme',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Uhrentürme',
	},
	{
		nounSingular: 'Gießerei',
		nounPlural: 'Gießereien',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Gießereien',
	},
	{
		nounSingular: 'Torhaus',
		nounPlural: 'Torhäuser',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Torhäuser',
	},
	{
		nounSingular: 'Haus',
		nounPlural: 'Häuser',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Häuser',
	},
	{
		nounSingular: 'Kerker',
		nounPlural: 'Kerker',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kerker',
	},
	{
		nounSingular: 'Mühle',
		nounPlural: 'Mühlen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Mühlen',
	},
	{
		nounSingular: 'Münzstätte',
		nounPlural: 'Münzstätten',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Münzstätten',
	},
	{
		nounSingular: 'Ruine',
		nounPlural: 'Ruinen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Ruinen',
	},
	{
		nounSingular: 'Laden',
		nounPlural: 'Läden',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S5',
		campaignSetting: 'Universal',
		tags: 'Läden',
	},
	{
		nounSingular: 'Pferdestall',
		nounPlural: 'Pferdeställe',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Pferdeställe',
	},
	{
		nounSingular: 'Taverne',
		nounPlural: 'Tavernen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Tavernen',
	},
	{
		nounSingular: 'Tempel',
		nounPlural: 'Tempel',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Tempel',
	},
	{
		nounSingular: 'Theater',
		nounPlural: 'Theater',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Theater',
	},
	{
		nounSingular: 'Universität',
		nounPlural: 'Universitäten',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Universitäten',
	},
];

// const buildingArray = [
// 	{
// 		nounSingular: 'Apotheke',
// 		nounPlural: 'Apotheken',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Apotheken',
// 	},
// 	{
// 		nounSingular: 'Schießstand',
// 		nounPlural: 'Schießstände',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'maskulinum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S1',
// 		campaignSetting: 'Universal',
// 		tags: 'Schießstände',
// 	},
// 	{
// 		nounSingular: 'Arena',
// 		nounPlural: 'Arenen',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Arenen',
// 	},
// 	{
// 		nounSingular: 'Waffenkammer',
// 		nounPlural: 'Waffenkammern',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Waffenkammern',
// 	},
// 	{
// 		nounSingular: 'Bank',
// 		nounPlural: 'Bänke',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'S3',
// 		campaignSetting: 'Universal',
// 		tags: 'Bänke',
// 	},
// 	{
// 		nounSingular: 'Kaserne',
// 		nounPlural: 'Kasernen',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Kasernen',
// 	},
// 	{
// 		nounSingular: 'Uhrenturm',
// 		nounPlural: 'Uhrentürme',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'maskulinum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S1',
// 		campaignSetting: 'Universal',
// 		tags: 'Uhrentürme',
// 	},
// 	{
// 		nounSingular: 'Gießerei',
// 		nounPlural: 'Gießereien',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Gießereien',
// 	},
// 	{
// 		nounSingular: 'Torhaus',
// 		nounPlural: 'Torhäuser',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'neutrum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S2',
// 		campaignSetting: 'Universal',
// 		tags: 'Torhäuser',
// 	},
// 	{
// 		nounSingular: 'Haus',
// 		nounPlural: 'Häuser',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'neutrum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S2',
// 		campaignSetting: 'Universal',
// 		tags: 'Häuser',
// 	},
// 	{
// 		nounSingular: 'Kerker',
// 		nounPlural: 'Kerker',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'maskulinum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S6',
// 		campaignSetting: 'Universal',
// 		tags: 'Kerker',
// 	},
// 	{
// 		nounSingular: 'Mühle',
// 		nounPlural: 'Mühlen',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Mühlen',
// 	},
// 	{
// 		nounSingular: 'Münzstätte',
// 		nounPlural: 'Münzstätten',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Münzstätten',
// 	},
// 	{
// 		nounSingular: 'Ruine',
// 		nounPlural: 'Ruinen',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Ruinen',
// 	},
// 	{
// 		nounSingular: 'Laden',
// 		nounPlural: 'Läden',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'maskulinum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S5',
// 		campaignSetting: 'Universal',
// 		tags: 'Läden',
// 	},
// 	{
// 		nounSingular: 'Pferdestall',
// 		nounPlural: 'Pferdeställe',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'maskulinum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S1',
// 		campaignSetting: 'Universal',
// 		tags: 'Pferdeställe',
// 	},
// 	{
// 		nounSingular: 'Taverne',
// 		nounPlural: 'Tavernen',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Tavernen',
// 	},
// 	{
// 		nounSingular: 'Tempel',
// 		nounPlural: 'Tempel',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'maskulinum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S6',
// 		campaignSetting: 'Universal',
// 		tags: 'Tempel',
// 	},
// 	{
// 		nounSingular: 'Theater',
// 		nounPlural: 'Theater',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'neutrum',
// 		declinationRule: 'starkeDeklination',
// 		declinationPattern: 'S6',
// 		campaignSetting: 'Universal',
// 		tags: 'Theater',
// 	},
// 	{
// 		nounSingular: 'Universität',
// 		nounPlural: 'Universitäten',
// 		adjective: '',
// 		prefix: '',
// 		suffix: '',
// 		nounGender: 'femininum',
// 		declinationRule: 'schwacheDeklination',
// 		declinationPattern: 'W2',
// 		campaignSetting: 'Universal',
// 		tags: 'Universitäten',
// 	},
// ];
