const classArray = [
	{
		singular: 'Barbar',
		plural: 'Barbaren',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Krieger,Barbaren',
	},
	{
		singular: 'Barde',
		plural: 'Barden',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Experten,Barden',
	},
	{
		singular: 'Druide',
		plural: 'Druiden',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Priester,Druiden',
	},
	{
		singular: 'Hexenmeister',
		plural: 'Hexenmeister',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Arkanisten,Hexenmeister',
	},
	{
		singular: 'Kämpfer',
		plural: 'Kämpfer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Krieger,Kämpfer',
	},
	{
		singular: 'Kleriker',
		plural: 'Kleriker',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Priester,Kleriker',
	},
	{
		singular: 'Magier',
		plural: 'Magier',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Arkanisten,Magier',
	},
	{
		singular: 'Mönch',
		plural: 'Mönche',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Krieger,Mönche',
	},
	{
		singular: 'Paladin',
		plural: 'Paladine',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Priester,Paladine',
	},
	{
		singular: 'Schurke',
		plural: 'Schurken',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Experten,Schurken',
	},
	{
		singular: 'Waldläufer',
		plural: 'Waldläufer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Experten,Waldläufer',
	},
	{
		singular: 'Zauberer',
		plural: 'Zauberer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Arkanisten,Zauberer',
	},
	{
		singular: 'Magieschmied',
		plural: 'Magieschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Arkanisten,Magieschmiede',
	},
	{
		singular: 'Blutjäger',
		plural: 'Blutjäger',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Krieger,Blutjäger',
	},
];
