const classArray = [
	{
		nounSingular: 'Barbar',
		nounPlural: 'Barbaren',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Krieger,Barbaren',
	},
	{
		nounSingular: 'Barde',
		nounPlural: 'Barden',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Experten,Barden',
	},
	{
		nounSingular: 'Druide',
		nounPlural: 'Druiden',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Priester,Druiden',
	},
	{
		nounSingular: 'Hexenmeister',
		nounPlural: 'Hexenmeister',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Arkanisten,Hexenmeister',
	},
	{
		nounSingular: 'Kämpfer',
		nounPlural: 'Kämpfer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Krieger,Kämpfer',
	},
	{
		nounSingular: 'Kleriker',
		nounPlural: 'Kleriker',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Priester,Kleriker',
	},
	{
		nounSingular: 'Magier',
		nounPlural: 'Magier',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Arkanisten,Magier',
	},
	{
		nounSingular: 'Mönch',
		nounPlural: 'Mönche',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Krieger,Mönche',
	},
	{
		nounSingular: 'Paladin',
		nounPlural: 'Paladine',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Priester,Paladine',
	},
	{
		nounSingular: 'Schurke',
		nounPlural: 'Schurken',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Experten,Schurken',
	},
	{
		nounSingular: 'Waldläufer',
		nounPlural: 'Waldläufer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Experten,Waldläufer',
	},
	{
		nounSingular: 'Zauberer',
		nounPlural: 'Zauberer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Arkanisten,Zauberer',
	},
	{
		nounSingular: 'Magieschmied',
		nounPlural: 'Magieschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Arkanisten,Magieschmiede',
	},
	{
		nounSingular: 'Blutjäger',
		nounPlural: 'Blutjäger',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Krieger,Blutjäger',
	},
];
