const creatureTypeArray = [
	{
		nounSingular: 'Aberration',
		nounPlural: 'Aberrationen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Aberrationen',
	},
	{
		nounSingular: 'Tier',
		nounPlural: 'Tiere',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Tiere',
	},
	{
		nounSingular: 'Himmlische',
		nounPlural: 'Himmlische',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Himmlische',
	},
	{
		nounSingular: 'Konstrukt',
		nounPlural: 'Konstrukte',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Konstrukte',
	},
	{
		nounSingular: 'Drache',
		nounPlural: 'Drachen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Drachen',
	},
	{
		nounSingular: 'Elementar',
		nounPlural: 'Elementare',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Elementare',
	},
	{
		nounSingular: 'Feenwesen',
		nounPlural: 'Feenwesen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Feenwesen',
	},
	{
		nounSingular: 'Unhold',
		nounPlural: 'Unholde',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Unholde',
	},
	{
		nounSingular: 'Riese',
		nounPlural: 'Riesen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Riesen',
	},
	{
		nounSingular: 'Humanoide',
		nounPlural: 'Humanoide',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Humanoide',
	},
	{
		nounSingular: 'Monstrosität',
		nounPlural: 'Monstrositäten',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Monstrositäten',
	},
	{
		nounSingular: 'Schlick',
		nounPlural: 'Schlicke',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Schlicke',
	},
	{
		nounSingular: 'Pflanze',
		nounPlural: 'Pflanzen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Pflanzen',
	},
	{
		nounSingular: 'Untote',
		nounPlural: 'Untote',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Untote',
	},
];
