const creatureTypeArray = [
	{
		singular: 'Aberration',
		plural: 'Aberrationen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Aberrationen',
	},
	{
		singular: 'Tier',
		plural: 'Tiere',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Tiere',
	},
	{
		singular: 'Himmlische',
		plural: 'Himmlische',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Himmlische',
	},
	{
		singular: 'Konstrukt',
		plural: 'Konstrukte',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Konstrukte',
	},
	{
		singular: 'Drache',
		plural: 'Drachen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Drachen',
	},
	{
		singular: 'Elementar',
		plural: 'Elementare',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Elementare',
	},
	{
		singular: 'Feenwesen',
		plural: 'Feenwesen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Feenwesen',
	},
	{
		singular: 'Unhold',
		plural: 'Unholde',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Unholde',
	},
	{
		singular: 'Riese',
		plural: 'Riesen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Riesen',
	},
	{
		singular: 'Humanoide',
		plural: 'Humanoide',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Humanoide',
	},
	{
		singular: 'Monstrosität',
		plural: 'Monstrositäten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Monstrositäten',
	},
	{
		singular: 'Schlick',
		plural: 'Schlicke',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Schlicke',
	},
	{
		singular: 'Pflanze',
		plural: 'Pflanzen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Pflanzen',
	},
	{
		singular: 'Untote',
		plural: 'Untote',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Kreaturen,Untote',
	},
];
