const eventArray = [
	{
		nounSingular: 'Hinterhalt',
		nounPlural: 'Hinterhalte',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Hinterhalte',
	},
	{
		nounSingular: 'Verbannung',
		nounPlural: 'Verbannungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Verbannungen',
	},
	{
		nounSingular: 'Geburt',
		nounPlural: 'Geburten',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Geburten',
	},
	{
		nounSingular: 'Ausbruch',
		nounPlural: 'Ausbrüche',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Ausbrüche',
	},
	{
		nounSingular: 'Gefangennahme',
		nounPlural: 'Gefangennahmen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Gefangennahmen',
	},
	{
		nounSingular: 'Errichtung',
		nounPlural: 'Errichtungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Errichtungen',
	},
	{
		nounSingular: 'Tod',
		nounPlural: 'Tode',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Tode',
	},
	{
		nounSingular: 'Bezwingung',
		nounPlural: 'Bezwingungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Bezwingungen',
	},
	{
		nounSingular: 'Zerstörung',
		nounPlural: 'Zerstörungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Zerstörungen',
	},
	{
		nounSingular: 'Vernichtung',
		nounPlural: 'Vernichtungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Vernichtungen',
	},
	{
		nounSingular: 'Explosion',
		nounPlural: 'Explosionen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Explosionen',
	},
	{
		nounSingular: 'Gründung',
		nounPlural: 'Gründungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Gründungen',
	},
	{
		nounSingular: 'Heilung',
		nounPlural: 'Heilungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Heilungen',
	},
	{
		nounSingular: 'Genesung',
		nounPlural: 'Genesungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Genesungen',
	},
	{
		nounSingular: 'Befreiung',
		nounPlural: 'Befreiungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Befreiungen',
	},
	{
		nounSingular: 'Wunder',
		nounPlural: 'Wunder',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Wunder',
	},
	{
		nounSingular: 'Plage',
		nounPlural: 'Plagen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Plagen',
	},
	{
		nounSingular: 'Sieg',
		nounPlural: 'Siege',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Siege',
	},
	{
		nounSingular: 'Hochzeit',
		nounPlural: 'Hochzeiten',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Hochzeiten',
	},
	{
		nounSingular: 'Verwundung',
		nounPlural: 'Verwundungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Verwundungen',
	},
];
