const metalArray = [
	{
		nounSingular: 'Aluminium',
		nounPlural: 'Aluminium',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Aluminium',
	},
	{
		nounSingular: 'Messing',
		nounPlural: 'Messing',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Messing',
	},
	{
		nounSingular: 'Bronze',
		nounPlural: 'Bronze',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Bronze',
	},
	{
		nounSingular: 'Kobalt',
		nounPlural: 'Kobalt',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Kobalt',
	},
	{
		nounSingular: 'Kupfer',
		nounPlural: 'Kupfer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Kupfer',
	},
	{
		nounSingular: 'Gold',
		nounPlural: 'Gold',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Gold',
	},
	{
		nounSingular: 'Iridium',
		nounPlural: 'Iridium',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Iridium',
	},
	{
		nounSingular: 'Eisen',
		nounPlural: 'Eisen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Eisen',
	},
	{
		nounSingular: 'Blei',
		nounPlural: 'Blei',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Blei',
	},
	{
		nounSingular: 'Magnesium',
		nounPlural: 'Magnesium',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Magnesium',
	},
	{
		nounSingular: 'Quecksilber',
		nounPlural: 'Quecksilber',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Quecksilber',
	},
	{
		nounSingular: 'Nickel',
		nounPlural: 'Nickel',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Nickel',
	},
	{
		nounSingular: 'Platin',
		nounPlural: 'Platin',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Platin',
	},
	{
		nounSingular: 'Silber',
		nounPlural: 'Silber',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Silber',
	},
	{
		nounSingular: 'Stahl',
		nounPlural: 'Stahl',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Stahl',
	},
	{
		nounSingular: 'Zinn',
		nounPlural: 'Zinn',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Zinn',
	},
	{
		nounSingular: 'Wolfram',
		nounPlural: 'Wolfram',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Wolfram',
	},
	{
		nounSingular: 'Uran',
		nounPlural: 'Uran',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Uran',
	},
	{
		nounSingular: 'Zink',
		nounPlural: 'Zink',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Zink',
	},
	{
		nounSingular: 'Elektrum',
		nounPlural: 'Elektrum',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Elektrum',
	},
];
