const metalArray = [
	{
		singular: 'Aluminium',
		plural: 'Aluminium',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Aluminium',
	},
	{
		singular: 'Messing',
		plural: 'Messing',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Messing',
	},
	{
		singular: 'Bronze',
		plural: 'Bronze',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Bronze',
	},
	{
		singular: 'Kobalt',
		plural: 'Kobalt',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Kobalt',
	},
	{
		singular: 'Kupfer',
		plural: 'Kupfer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Kupfer',
	},
	{
		singular: 'Gold',
		plural: 'Gold',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Gold',
	},
	{
		singular: 'Iridium',
		plural: 'Iridium',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Iridium',
	},
	{
		singular: 'Eisen',
		plural: 'Eisen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Eisen',
	},
	{
		singular: 'Blei',
		plural: 'Blei',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Blei',
	},
	{
		singular: 'Magnesium',
		plural: 'Magnesium',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Magnesium',
	},
	{
		singular: 'Quecksilber',
		plural: 'Quecksilber',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Quecksilber',
	},
	{
		singular: 'Nickel',
		plural: 'Nickel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Nickel',
	},
	{
		singular: 'Platin',
		plural: 'Platin',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Platin',
	},
	{
		singular: 'Silber',
		plural: 'Silber',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Silber',
	},
	{
		singular: 'Stahl',
		plural: 'Stahl',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Stahl',
	},
	{
		singular: 'Zinn',
		plural: 'Zinn',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Zinn',
	},
	{
		singular: 'Wolfram',
		plural: 'Wolfram',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Wolfram',
	},
	{
		singular: 'Uran',
		plural: 'Uran',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Uran',
	},
	{
		singular: 'Zink',
		plural: 'Zink',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Zink',
	},
	{
		singular: 'Elektrum',
		plural: 'Elektrum',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Elektrum',
	},
];
