const mountainRangeArray = [
	{
		singular: 'Graugipfelberge',
		plural: 'Graugipfelberge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		number: 'plural',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Vergessene Reiche',
		tags: 'Vergessene Reiche',
	},
	{
		singular: 'Sternberge',
		plural: 'Sternberge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		number: 'plural',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Vergessene Reiche',
		tags: 'Vergessene Reiche',
	},
	{
		singular: 'Grat',
		plural: 'Grat',
		adjective: '',
		prefix: '',
		suffix: 'der Welt',
		gender: 'maskulinum',
		number: 'singular',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Vergessene Reiche',
		tags: 'Vergessene Reiche',
	},
	{
		singular: 'Schwertberge',
		plural: 'Schwertberge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		number: 'plural',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Vergessene Reiche',
		tags: 'Vergessene Reiche',
	},
	{
		singular: 'Rauvinberge',
		plural: 'Rauvinberge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		number: 'plural',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Vergessene Reiche',
		tags: 'Vergessene Reiche',
	},
];
