const mountainRangeArray = [
	{
		nounSingular: 'Graugipfelberge',
		nounPlural: 'Graugipfelberge',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		nounNumber: 'plural',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Vergessene Reiche',
		tags: 'Vergessene Reiche',
	},
	{
		nounSingular: 'Sternberge',
		nounPlural: 'Sternberge',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		nounNumber: 'plural',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Vergessene Reiche',
		tags: 'Vergessene Reiche',
	},
	{
		nounSingular: 'Grat',
		nounPlural: 'Grat',
		adjective: '',
		prefix: '',
		suffix: 'der Welt',
		nounGender: 'maskulinum',
		nounNumber: 'singular',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Vergessene Reiche',
		tags: 'Vergessene Reiche',
	},
	{
		nounSingular: 'Schwertberge',
		nounPlural: 'Schwertberge',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		nounNumber: 'plural',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Vergessene Reiche',
		tags: 'Vergessene Reiche',
	},
	{
		nounSingular: 'Rauvinberge',
		nounPlural: 'Rauvinberge',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		nounNumber: 'plural',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Vergessene Reiche',
		tags: 'Vergessene Reiche',
	},
];
