const professionArray = [
	{
		singular: 'Alchemist',
		plural: 'Alchemisten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Alchemisten',
	},
	{
		singular: 'Apotheker',
		plural: 'Apotheker',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Apotheker',
	},
	{
		singular: 'Architekt',
		plural: 'Architekten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Architekten',
	},
	{
		singular: 'Auftragsmörder',
		plural: 'Auftragsmörder',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Auftragsmörder',
	},
	{
		singular: 'Bäcker',
		plural: 'Bäcker',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Bäcker',
	},
	{
		singular: 'Bandit',
		plural: 'Banditen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Banditen',
	},
	{
		singular: 'Bogenmacher',
		plural: 'Bogenmacher',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Bogenmacher',
	},
	{
		singular: 'Bürgermeister',
		plural: 'Bürgermeister',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Bürgermeister',
	},
	{
		singular: 'Barde',
		plural: 'Barden',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Barden',
	},
	{
		singular: 'Bauer',
		plural: 'Bauern',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Bauern',
	},
	{
		singular: 'Bettler',
		plural: 'Bettler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Bettler',
	},
	{
		singular: 'Butler',
		plural: 'Butler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Butler',
	},
	{
		singular: 'Diener',
		plural: 'Diener',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Diener',
	},
	{
		singular: 'Bogenschütze',
		plural: 'Bogenschützen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Bogenschützen',
	},
	{
		singular: 'Bote',
		plural: 'Boten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Boten',
	},
	{
		singular: 'Brauer',
		plural: 'Brauer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Brauer',
	},
	{
		singular: 'Fallensteller',
		plural: 'Fallensteller',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Fallensteller',
	},
	{
		singular: 'Fischer',
		plural: 'Fischer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Fischer',
	},
	{
		singular: 'Fremdenführer',
		plural: 'Fremdenführer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Fremdenführer',
	},
	{
		singular: 'Diplomat',
		plural: 'Diplomaten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Diplomaten',
	},
	{
		singular: 'Edelsteinschneider',
		plural: 'Edelsteinschneider',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Edelsteinschneider',
	},
	{
		singular: 'Gärtner',
		plural: 'Gärtner',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Gärtner',
	},
	{
		singular: 'Gerber',
		plural: 'Gerber',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Gerber',
	},
	{
		singular: 'Glasbläser',
		plural: 'Glasbläser',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Glasbläser',
	},
	{
		singular: 'Hellseher',
		plural: 'Hellseher',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Hellseher',
	},
	{
		singular: 'Jagdaufseher',
		plural: 'Jagdaufseher',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Jagdaufseher',
	},
	{
		singular: 'Gelehrte',
		plural: 'Gelehrte',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Gelehrte',
	},
	{
		singular: 'Jäger',
		plural: 'Jäger',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Jäger',
	},
	{
		singular: 'Kerzenmacher',
		plural: 'Kerzenmacher',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kerzenmacher',
	},
	{
		singular: 'Gladiator',
		plural: 'Gladiatoren',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'gemischteDeklination',
		declinationPattern: 'W3',
		campaignSetting: 'Universal',
		tags: 'Gladiatoren',
	},
	{
		singular: 'Kleriker',
		plural: 'Kleriker',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kleriker',
	},
	{
		singular: 'Kräuterkundler',
		plural: 'Kräuterkundler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kräuterkundler',
	},
	{
		singular: 'Krieger',
		plural: 'Krieger',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Krieger',
	},
	{
		singular: 'Hebamme',
		plural: 'Hebammen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Hebammen',
	},
	{
		singular: 'Heiler',
		plural: 'Heiler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Heiler',
	},
	{
		singular: 'Künstler',
		plural: 'Künstler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Künstler',
	},
	{
		singular: 'Kürschner',
		plural: 'Kürschner',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kürschner',
	},
	{
		singular: 'Kutscher',
		plural: 'Kutscher',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kutscher',
	},
	{
		singular: 'Laternenanzünder',
		plural: 'Laternenanzünder',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Laternenanzünder',
	},
	{
		singular: 'Lederarbeiter',
		plural: 'Lederarbeiter',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Lederarbeiter',
	},
	{
		singular: 'Inquisitor',
		plural: 'Inquisitoren',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'gemischteDeklination',
		declinationPattern: 'W3',
		campaignSetting: 'Universal',
		tags: 'Inquisitoren',
	},
	{
		singular: 'Lehrer',
		plural: 'Lehrer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Lehrer',
	},
	{
		singular: 'Magier',
		plural: 'Magier',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Magier',
	},
	{
		singular: 'Metzger',
		plural: 'Metzger',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Metzger',
	},
	{
		singular: 'Orakel',
		plural: 'Orakel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Orakel',
	},
	{
		singular: 'Kartograph',
		plural: 'Kartographen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Kartographen',
	},
	{
		singular: 'Priester',
		plural: 'Priester',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Priester',
	},
	{
		singular: 'Sattler',
		plural: 'Sattler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Sattler',
	},
	{
		singular: 'Schäfer',
		plural: 'Schäfer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schäfer',
	},
	{
		singular: 'Schauspieler',
		plural: 'Schauspieler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schauspieler',
	},
	{
		singular: 'Schmuggler',
		plural: 'Schmuggler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schmuggler',
	},
	{
		singular: 'Schneider',
		plural: 'Schneider',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schneider',
	},
	{
		singular: 'Schreiber',
		plural: 'Schreiber',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schreiber',
	},
	{
		singular: 'Schreiner',
		plural: 'Schreiner',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schreiner',
	},
	{
		singular: 'Seher',
		plural: 'Seher',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Seher',
	},
	{
		singular: 'Töpferer',
		plural: 'Töpferer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Töpferer',
	},
	{
		singular: 'Torwächter',
		plural: 'Torwächter',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Torwächter',
	},
	{
		singular: 'Totengräber',
		plural: 'Totengräber',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Totengräber',
	},
	{
		singular: 'Unterhaltungskünstler',
		plural: 'Unterhaltungskünstler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Unterhaltungskünstler',
	},
	{
		singular: 'Wächter',
		plural: 'Wächter',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Wächter',
	},
	{
		singular: 'Wagenbauer',
		plural: 'Wagenbauer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Wagenbauer',
	},
	{
		singular: 'Waldläufer',
		plural: 'Waldläufer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Waldläufer',
	},
	{
		singular: 'Weber',
		plural: 'Weber',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Weber',
	},
	{
		singular: 'Wissenshüter',
		plural: 'Wissenshüter',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Wissenshüter',
	},
	{
		singular: 'Zauberer',
		plural: 'Zauberer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Zauberer',
	},
	{
		singular: 'Bankier',
		plural: 'Bankiers',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Bankiers',
	},
	{
		singular: 'Barbier',
		plural: 'Barbiere',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Barbiere',
	},
	{
		singular: 'Bischof',
		plural: 'Bischöfe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Bischöfe',
	},
	{
		singular: 'Forstwirt',
		plural: 'Forstwirte',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Forstwirte',
	},
	{
		singular: 'General',
		plural: 'Generäle',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Generäle',
	},
	{
		singular: 'Goldschmied',
		plural: 'Goldschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Goldschmiede',
	},
	{
		singular: 'Graveur',
		plural: 'Graveure',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Graveure',
	},
	{
		singular: 'Herold',
		plural: 'Herolde',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Herolde',
	},
	{
		singular: 'Hufschmied',
		plural: 'Hufschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Hufschmiede',
	},
	{
		singular: 'Hundedresseur',
		plural: 'Hundedresseure',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Hundedresseure',
	},
	{
		singular: 'Ingenieur',
		plural: 'Ingenieure',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Ingenieure',
	},
	{
		singular: 'Schurke',
		plural: 'Schurken',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Schurken',
	},
	{
		singular: 'Juwelier',
		plural: 'Juweliere',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Juweliere',
	},
	{
		singular: 'Kapitän',
		plural: 'Kapitäne',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Kapitäne',
	},
	{
		singular: 'Knecht',
		plural: 'Knechte',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Knechte',
	},
	{
		singular: 'Koch',
		plural: 'Köche',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Köche',
	},
	{
		singular: 'Soldat',
		plural: 'Soldaten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Soldaten',
	},
	{
		singular: 'Kurier',
		plural: 'Kuriere',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kuriere',
	},
	{
		singular: 'Theaterautor',
		plural: 'Theaterautoren',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'gemischteDeklination',
		declinationPattern: 'W3',
		campaignSetting: 'Universal',
		tags: 'Theaterautoren',
	},
	{
		singular: 'Mönch',
		plural: 'Mönche',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Mönche',
	},
	{
		singular: 'Kaufmann',
		plural: 'Kaufmänner',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Kaufmänner',
	},
	{
		singular: 'Rechtsanwalt',
		plural: 'Rechtsanwälte',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Rechtsanwälte',
	},
	{
		singular: 'Runenschmied',
		plural: 'Runenschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Runenschmiede',
	},
	{
		singular: 'Rüstungsschmied',
		plural: 'Rüstungsschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Rüstungsschmiede',
	},
	{
		singular: 'Schmied',
		plural: 'Schmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Schmiede',
	},
	{
		singular: 'Seemann',
		plural: 'Seemänner',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Seemänner',
	},
	{
		singular: 'Sekretär',
		plural: 'Sekretäre',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Sekretäre',
	},
	{
		singular: 'Silberschmied',
		plural: 'Silberschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Silberschmiede',
	},
	{
		singular: 'Steinmetz',
		plural: 'Steinmetze',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Steinmetze',
	},
	{
		singular: 'Tierdresseur',
		plural: 'Tierdresseure',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Tierdresseure',
	},
	{
		singular: 'Weise',
		plural: 'Weise',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Weise',
	},
	{
		singular: 'Wachmann',
		plural: 'Wachmänner',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Wachmänner',
	},
	{
		singular: 'Waffenschmied',
		plural: 'Waffenschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Waffenschmiede',
	},
	{
		singular: 'Wirt',
		plural: 'Wirte',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Wirte',
	},
	{
		singular: 'Zimmermann',
		plural: 'Zimmermänner',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Zimmermänner',
	},
];
