const professionArray = [
	{
		nounSingular: 'Alchemist',
		nounPlural: 'Alchemisten',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Alchemisten',
	},
	{
		nounSingular: 'Apotheker',
		nounPlural: 'Apotheker',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Apotheker',
	},
	{
		nounSingular: 'Architekt',
		nounPlural: 'Architekten',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Architekten',
	},
	{
		nounSingular: 'Auftragsmörder',
		nounPlural: 'Auftragsmörder',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Auftragsmörder',
	},
	{
		nounSingular: 'Bäcker',
		nounPlural: 'Bäcker',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Bäcker',
	},
	{
		nounSingular: 'Bandit',
		nounPlural: 'Banditen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Banditen',
	},
	{
		nounSingular: 'Bogenmacher',
		nounPlural: 'Bogenmacher',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Bogenmacher',
	},
	{
		nounSingular: 'Bürgermeister',
		nounPlural: 'Bürgermeister',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Bürgermeister',
	},
	{
		nounSingular: 'Barde',
		nounPlural: 'Barden',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Barden',
	},
	{
		nounSingular: 'Bauer',
		nounPlural: 'Bauern',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Bauern',
	},
	{
		nounSingular: 'Bettler',
		nounPlural: 'Bettler',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Bettler',
	},
	{
		nounSingular: 'Butler',
		nounPlural: 'Butler',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Butler',
	},
	{
		nounSingular: 'Diener',
		nounPlural: 'Diener',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Diener',
	},
	{
		nounSingular: 'Bogenschütze',
		nounPlural: 'Bogenschützen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Bogenschützen',
	},
	{
		nounSingular: 'Bote',
		nounPlural: 'Boten',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Boten',
	},
	{
		nounSingular: 'Brauer',
		nounPlural: 'Brauer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Brauer',
	},
	{
		nounSingular: 'Fallensteller',
		nounPlural: 'Fallensteller',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Fallensteller',
	},
	{
		nounSingular: 'Fischer',
		nounPlural: 'Fischer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Fischer',
	},
	{
		nounSingular: 'Fremdenführer',
		nounPlural: 'Fremdenführer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Fremdenführer',
	},
	{
		nounSingular: 'Diplomat',
		nounPlural: 'Diplomaten',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Diplomaten',
	},
	{
		nounSingular: 'Edelsteinschneider',
		nounPlural: 'Edelsteinschneider',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Edelsteinschneider',
	},
	{
		nounSingular: 'Gärtner',
		nounPlural: 'Gärtner',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Gärtner',
	},
	{
		nounSingular: 'Gerber',
		nounPlural: 'Gerber',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Gerber',
	},
	{
		nounSingular: 'Glasbläser',
		nounPlural: 'Glasbläser',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Glasbläser',
	},
	{
		nounSingular: 'Hellseher',
		nounPlural: 'Hellseher',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Hellseher',
	},
	{
		nounSingular: 'Jagdaufseher',
		nounPlural: 'Jagdaufseher',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Jagdaufseher',
	},
	{
		nounSingular: 'Gelehrte',
		nounPlural: 'Gelehrte',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Gelehrte',
	},
	{
		nounSingular: 'Jäger',
		nounPlural: 'Jäger',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Jäger',
	},
	{
		nounSingular: 'Kerzenmacher',
		nounPlural: 'Kerzenmacher',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kerzenmacher',
	},
	{
		nounSingular: 'Gladiator',
		nounPlural: 'Gladiatoren',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'gemischteDeklination',
		declinationPattern: 'W3',
		campaignSetting: 'Universal',
		tags: 'Gladiatoren',
	},
	{
		nounSingular: 'Kleriker',
		nounPlural: 'Kleriker',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kleriker',
	},
	{
		nounSingular: 'Kräuterkundler',
		nounPlural: 'Kräuterkundler',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kräuterkundler',
	},
	{
		nounSingular: 'Krieger',
		nounPlural: 'Krieger',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Krieger',
	},
	{
		nounSingular: 'Hebamme',
		nounPlural: 'Hebammen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Hebammen',
	},
	{
		nounSingular: 'Heiler',
		nounPlural: 'Heiler',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Heiler',
	},
	{
		nounSingular: 'Künstler',
		nounPlural: 'Künstler',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Künstler',
	},
	{
		nounSingular: 'Kürschner',
		nounPlural: 'Kürschner',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kürschner',
	},
	{
		nounSingular: 'Kutscher',
		nounPlural: 'Kutscher',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Kutscher',
	},
	{
		nounSingular: 'Laternenanzünder',
		nounPlural: 'Laternenanzünder',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Laternenanzünder',
	},
	{
		nounSingular: 'Lederarbeiter',
		nounPlural: 'Lederarbeiter',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Lederarbeiter',
	},
	{
		nounSingular: 'Inquisitor',
		nounPlural: 'Inquisitoren',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'gemischteDeklination',
		declinationPattern: 'W3',
		campaignSetting: 'Universal',
		tags: 'Inquisitoren',
	},
	{
		nounSingular: 'Lehrer',
		nounPlural: 'Lehrer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Lehrer',
	},
	{
		nounSingular: 'Magier',
		nounPlural: 'Magier',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Magier',
	},
	{
		nounSingular: 'Metzger',
		nounPlural: 'Metzger',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Metzger',
	},
	{
		nounSingular: 'Orakel',
		nounPlural: 'Orakel',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Orakel',
	},
	{
		nounSingular: 'Kartograph',
		nounPlural: 'Kartographen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Kartographen',
	},
	{
		nounSingular: 'Priester',
		nounPlural: 'Priester',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Priester',
	},
	{
		nounSingular: 'Sattler',
		nounPlural: 'Sattler',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Sattler',
	},
	{
		nounSingular: 'Schäfer',
		nounPlural: 'Schäfer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schäfer',
	},
	{
		nounSingular: 'Schauspieler',
		nounPlural: 'Schauspieler',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schauspieler',
	},
	{
		nounSingular: 'Schmuggler',
		nounPlural: 'Schmuggler',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schmuggler',
	},
	{
		nounSingular: 'Schneider',
		nounPlural: 'Schneider',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schneider',
	},
	{
		nounSingular: 'Schreiber',
		nounPlural: 'Schreiber',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schreiber',
	},
	{
		nounSingular: 'Schreiner',
		nounPlural: 'Schreiner',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Schreiner',
	},
	{
		nounSingular: 'Seher',
		nounPlural: 'Seher',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Seher',
	},
	{
		nounSingular: 'Töpferer',
		nounPlural: 'Töpferer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Töpferer',
	},
	{
		nounSingular: 'Torwächter',
		nounPlural: 'Torwächter',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Torwächter',
	},
	{
		nounSingular: 'Totengräber',
		nounPlural: 'Totengräber',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Totengräber',
	},
	{
		nounSingular: 'Unterhaltungskünstler',
		nounPlural: 'Unterhaltungskünstler',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Unterhaltungskünstler',
	},
	{
		nounSingular: 'Wächter',
		nounPlural: 'Wächter',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Wächter',
	},
	{
		nounSingular: 'Wagenbauer',
		nounPlural: 'Wagenbauer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Wagenbauer',
	},
	{
		nounSingular: 'Waldläufer',
		nounPlural: 'Waldläufer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Waldläufer',
	},
	{
		nounSingular: 'Weber',
		nounPlural: 'Weber',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Weber',
	},
	{
		nounSingular: 'Wissenshüter',
		nounPlural: 'Wissenshüter',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Wissenshüter',
	},
	{
		nounSingular: 'Zauberer',
		nounPlural: 'Zauberer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Zauberer',
	},
	{
		nounSingular: 'Bankier',
		nounPlural: 'Bankiers',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Bankiers',
	},
	{
		nounSingular: 'Barbier',
		nounPlural: 'Barbiere',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Barbiere',
	},
	{
		nounSingular: 'Bischof',
		nounPlural: 'Bischöfe',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Bischöfe',
	},
	{
		nounSingular: 'Forstwirt',
		nounPlural: 'Forstwirte',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Forstwirte',
	},
	{
		nounSingular: 'General',
		nounPlural: 'Generäle',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Generäle',
	},
	{
		nounSingular: 'Goldschmied',
		nounPlural: 'Goldschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Goldschmiede',
	},
	{
		nounSingular: 'Graveur',
		nounPlural: 'Graveure',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Graveure',
	},
	{
		nounSingular: 'Herold',
		nounPlural: 'Herolde',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Herolde',
	},
	{
		nounSingular: 'Hufschmied',
		nounPlural: 'Hufschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Hufschmiede',
	},
	{
		nounSingular: 'Hundedresseur',
		nounPlural: 'Hundedresseure',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Hundedresseure',
	},
	{
		nounSingular: 'Ingenieur',
		nounPlural: 'Ingenieure',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Ingenieure',
	},
	{
		nounSingular: 'Schurke',
		nounPlural: 'Schurken',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Schurken',
	},
	{
		nounSingular: 'Juwelier',
		nounPlural: 'Juweliere',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Juweliere',
	},
	{
		nounSingular: 'Kapitän',
		nounPlural: 'Kapitäne',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Kapitäne',
	},
	{
		nounSingular: 'Knecht',
		nounPlural: 'Knechte',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Knechte',
	},
	{
		nounSingular: 'Koch',
		nounPlural: 'Köche',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Köche',
	},
	{
		nounSingular: 'Soldat',
		nounPlural: 'Soldaten',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Soldaten',
	},
	{
		nounSingular: 'Kurier',
		nounPlural: 'Kuriere',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Kuriere',
	},
	{
		nounSingular: 'Theaterautor',
		nounPlural: 'Theaterautoren',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'gemischteDeklination',
		declinationPattern: 'W3',
		campaignSetting: 'Universal',
		tags: 'Theaterautoren',
	},
	{
		nounSingular: 'Mönch',
		nounPlural: 'Mönche',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Mönche',
	},
	{
		nounSingular: 'Kaufmann',
		nounPlural: 'Kaufmänner',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Kaufmänner',
	},
	{
		nounSingular: 'Rechtsanwalt',
		nounPlural: 'Rechtsanwälte',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Rechtsanwälte',
	},
	{
		nounSingular: 'Runenschmied',
		nounPlural: 'Runenschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Runenschmiede',
	},
	{
		nounSingular: 'Rüstungsschmied',
		nounPlural: 'Rüstungsschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Rüstungsschmiede',
	},
	{
		nounSingular: 'Schmied',
		nounPlural: 'Schmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Schmiede',
	},
	{
		nounSingular: 'Seemann',
		nounPlural: 'Seemänner',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Seemänner',
	},
	{
		nounSingular: 'Sekretär',
		nounPlural: 'Sekretäre',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Sekretäre',
	},
	{
		nounSingular: 'Silberschmied',
		nounPlural: 'Silberschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Silberschmiede',
	},
	{
		nounSingular: 'Steinmetz',
		nounPlural: 'Steinmetze',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Steinmetze',
	},
	{
		nounSingular: 'Tierdresseur',
		nounPlural: 'Tierdresseure',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Tierdresseure',
	},
	{
		nounSingular: 'Weise',
		nounPlural: 'Weise',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Weise',
	},
	{
		nounSingular: 'Wachmann',
		nounPlural: 'Wachmänner',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Wachmänner',
	},
	{
		nounSingular: 'Waffenschmied',
		nounPlural: 'Waffenschmiede',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Waffenschmiede',
	},
	{
		nounSingular: 'Wirt',
		nounPlural: 'Wirte',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Wirte',
	},
	{
		nounSingular: 'Zimmermann',
		nounPlural: 'Zimmermänner',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Zimmermänner',
	},
];
