const raceArray = [
	{
		singular: 'Aarakocra',
		plural: 'Aarakocra',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Aarakocra',
	},
	{
		singular: 'Aasimar',
		plural: 'Aasimar',
		adjective: 'gefallene',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Aasimar',
	},
	{
		singular: 'Astralelf',
		plural: 'Astralelfen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Astralelfen',
	},
	{
		singular: 'Autognom',
		plural: 'Autognome',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Konstrukt,Autognome',
	},
	{
		singular: 'Beschützer-Aasimar',
		plural: 'Beschützer-Aasimar',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Beschützer-Aasimar',
	},
	{
		singular: 'Blasself',
		plural: 'Blasselfen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Blasselfen',
	},
	{
		singular: 'Bullywug',
		plural: 'Bullywugs',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Bullywug',
	},
	{
		singular: 'Dämmerungself',
		plural: 'Dämmerungselfen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Dämmerungselfen',
	},
	{
		singular: 'Derro',
		plural: 'Derro',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Derro',
	},
	{
		singular: 'Dhampir',
		plural: 'Dhampire',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Dhampire',
	},
	{
		singular: 'Drachenblütige',
		plural: 'Drachenblütige',
		adjective: 'chromatische',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Drachenblütige,Chromatische Drachenblütige',
	},
	{
		singular: 'Drachenblütige',
		plural: 'Drachenblütige',
		adjective: 'drachlingsblütige',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Drachenblütige,Drachlingsblütige Drachenblütige',
	},
	{
		singular: 'Drachenblütige',
		plural: 'Drachenblütige',
		adjective: 'metallische',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Drachenblütige,Metallische Drachenblütige',
	},
	{
		singular: 'Dunkelelf',
		plural: 'Dunkelelfen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Dunkelelfen',
	},
	{
		singular: 'Dunkelzwerg',
		plural: 'Dunkelzwerge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Zwerge,Dunkelzwerge',
	},
	{
		singular: 'Echsenmensch',
		plural: 'Echsenmenschen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Echsenmenschen',
	},
	{
		singular: 'Edelstein-Drachenblütige',
		plural: 'Edelstein-Drachenblütige',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Drachenblütige,Edelstein-Drachenblütige',
	},
	{
		singular: 'Eladrin',
		plural: 'Eladrin',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Eladrin',
	},
	{
		singular: 'Erd-Genasi',
		plural: 'Erd-Genasi',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Genasi,Erd-Genasi',
	},
	{
		singular: 'Fee',
		plural: 'Feen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Feenwesen,Feen',
	},
	{
		singular: 'Felsengnom',
		plural: 'Felsengnome',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gnome,Felsengnome',
	},
	{
		singular: 'Feuer-Genasi',
		plural: 'Feuer-Genasi',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Genasi,Feuer-Genasi',
	},
	{
		singular: 'Feuermolch',
		plural: 'Feuermolche',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Feuermolche',
	},
	{
		singular: 'Firbolg',
		plural: 'Firbolgs',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Firbolg',
	},
	{
		singular: 'Flinkläufer-Wandler',
		plural: 'Flinkläufer-Wandler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gestaltwandler,Wandler,Flinkläufer-Wandler',
	},
	{
		singular: 'Gebirgzwerg',
		plural: 'Gebirgzwerge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Zwerge,Gebirgzwerge',
	},
	{
		singular: 'Geißel-Aasimar',
		plural: 'Geißel-Aasimar',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Aasimar,Geißel-Aasimar',
	},
	{
		singular: 'Geisterwaisen-Halbling',
		plural: 'Geisterwaisen-Halblinge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Halblinge,Geisterwaisen-Halblinge',
	},
	{
		singular: 'Giff',
		plural: 'Giff',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Giff',
	},
	{
		singular: 'Githyanki',
		plural: 'Githyanki',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Githyanki',
	},
	{
		singular: 'Githzerai',
		plural: 'Githzerai',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Githzerai',
	},
	{
		singular: 'Gnoll',
		plural: 'Gnolle',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gnolle',
	},
	{
		singular: 'Goblin',
		plural: 'Goblins',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Goblinoide,Goblins',
	},
	{
		singular: 'Goliath',
		plural: 'Goliaths',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Goliaths',
	},
	{
		singular: 'Grimlock',
		plural: 'Grimlocks',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Grimlocks',
	},
	{
		singular: 'Grottenschrat',
		plural: 'Grottenschrate',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Goblinoide,Grottenschrate',
	},
	{
		singular: 'Grung',
		plural: 'Grungs',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Grung',
	},
	{
		singular: 'Hadozee',
		plural: 'Hadozee',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Hadozee',
	},
	{
		singular: 'Halbdrache',
		plural: 'Halbdrachen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Halbdrachen',
	},
	{
		singular: 'Halbelf',
		plural: 'Halbelfen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Halbelfen',
	},
	{
		singular: 'Halbling',
		plural: 'Halblinge',
		adjective: 'stämmige',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Halblinge,stämmige Halblinge',
	},
	{
		singular: 'Halbork',
		plural: 'Halborks',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Orks,Halborks',
	},
	{
		singular: 'Harengon',
		plural: 'Harengon',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Harengon',
	},
	{
		singular: 'Hexenblütige',
		plural: 'Hexenblütige',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Feenwesen,Hexenblütige',
	},
	{
		singular: 'Hobgoblin',
		plural: 'Hobgoblins',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Goblinoide,Hobgoblins',
	},
	{
		singular: 'Hochelf',
		plural: 'Hochelfen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Hochelfen',
	},
	{
		singular: 'Hügelzwerg',
		plural: 'Hügelzwerge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Zwerge,Hügelzwerge',
	},
	{
		singular: 'Kalashtar',
		plural: 'Kalashtar',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kalashtar',
	},
	{
		singular: 'Kender',
		plural: 'Kender',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kender',
	},
	{
		singular: 'Kenku',
		plural: 'Kenkus',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kenkus',
	},
	{
		singular: 'Kobold',
		plural: 'Kobolde',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kobolde',
	},
	{
		singular: 'Kraul',
		plural: 'Kraul',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kraul',
	},
	{
		singular: 'Kriegsgeschmiedete',
		plural: 'Kriegsgeschmiedete',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kriegsgeschmiedete',
	},
	{
		singular: 'Kuo-Toa',
		plural: 'Kuo-Toas',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kuo-Toas',
	},
	{
		singular: 'Langzahn-Wandler',
		plural: 'Langzahn-Wandler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gestaltwandler,Wandler,Langzahn-Wandler',
	},
	{
		singular: 'Lavakind',
		plural: 'Lavakinder',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Lavakinder',
	},
	{
		singular: 'Leichtfuß-Halbling',
		plural: 'Leichtfuß-Halblinge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Halblinge,Leichtfuß-Halblinge',
	},
	{
		singular: 'Leonide',
		plural: 'Leoniden',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Leoniden',
	},
	{
		singular: 'Locathah',
		plural: 'Locathah',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Locathah',
	},
	{
		singular: 'Lotusden-Halbling',
		plural: 'Lotusden-Halblinge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Halblinge,Lotusden-Halblinge',
	},
	{
		singular: 'Loxodon',
		plural: 'Loxodon',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Loxodon',
	},
	{
		singular: 'Luft-Genasi',
		plural: 'Luft-Genasi',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Genasi,Luft-Genasi',
	},
	{
		singular: 'Lykanthrop',
		plural: 'Lykanthropen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gestaltwandler,Lykanthropen',
	},
	{
		singular: 'Mazer',
		plural: 'Mazer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Mazer',
	},
	{
		singular: 'Meereself',
		plural: 'Meereselfen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Meereselfen',
	},
	{
		singular: 'Meervolk',
		plural: 'Meervölker',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Meervölker',
	},
	{
		singular: 'Mensch',
		plural: 'Menschen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Menschen',
	},
	{
		singular: 'Minotaur',
		plural: 'Minotauren',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Minotauren',
	},
	{
		singular: 'Mischlingsvolk',
		plural: 'Mischlingsvölker',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Mischlingsvölker',
	},
	{
		singular: 'Nagpa',
		plural: 'Nagpas',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Nagpa',
	},
	{
		singular: 'Nilbog',
		plural: 'Nilbogs',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Nilbogs',
	},
	{
		singular: 'Ork',
		plural: 'Orks',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Orks',
	},
	{
		singular: 'Orog',
		plural: 'Orogs',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Orog',
	},
	{
		singular: 'Plasmoide',
		plural: 'Plasmoiden',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Schlicke,Plasmoiden',
	},
	{
		singular: 'Quaggoth',
		plural: 'Quaggoths',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Quaggoth',
	},
	{
		singular: 'Ravenit-Drachenblütige',
		plural: 'Ravenit-Drachenblütige',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Drachenblütige,Ravenit-Drachenblütige',
	},
	{
		singular: 'Sahuagin',
		plural: 'Sahuagin',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Sahuagin',
	},
	{
		singular: 'Satyr',
		plural: 'Satyren',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Feenwesen,Satyren',
	},
	{
		singular: 'Saurianer',
		plural: 'Saurianer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Saurianer',
	},
	{
		singular: 'Shadar-Kai',
		plural: 'Shadar-Kai',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Shadar-Kai',
	},
	{
		singular: 'Simic-Hybride',
		plural: 'Simic-Hybriden',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Simic-Hybriden',
	},
	{
		singular: 'Tabaxi',
		plural: 'Tabaxi',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Tabaxi',
	},
	{
		singular: 'Thri-Kreen',
		plural: 'Thri-Kreen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Thri-Kreen',
	},
	{
		singular: 'Tiefengnom',
		plural: 'Tiefengnome',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gnome,Tiefengnome',
	},
	{
		singular: 'Tiefling',
		plural: 'Tieflinge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Tieflinge',
	},
	{
		singular: 'Tierhaut-Wandler',
		plural: 'Tierhaut-Wandler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gestaltwandler,Wandler,Tierhaut-Wandler',
	},
	{
		singular: 'Tortel',
		plural: 'Tortel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Tortel',
	},
	{
		singular: 'Triton',
		plural: 'Tritonen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Triton',
	},
	{
		singular: 'Troglodyt',
		plural: 'Troglodyten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Troglodyten',
	},
	{
		singular: 'Uhle',
		plural: 'Uhlen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Uhlen',
	},
	{
		singular: 'Vedalken',
		plural: 'Vedalken',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Vedalken',
	},
	{
		singular: 'Verdan',
		plural: 'Verdan',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Goblinoide,Verdan',
	},
	{
		singular: 'Waldelf',
		plural: 'Waldelfen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Waldelfen',
	},
	{
		singular: 'Waldgnom',
		plural: 'Waldgnome',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gnome,Waldgnome',
	},
	{
		singular: 'Wasser-Genasi',
		plural: 'Wasser-Genasi',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Genasi,Wasser-Genasi',
	},
	{
		singular: 'Wechselbalg',
		plural: 'Wechselbälger',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gestaltwandler,Wechselbälger',
	},
	{
		singular: 'Wiedergeborene',
		plural: 'Wiedergeborene',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Wiedergeborene',
	},
	{
		singular: 'Wildläufer-Wandler',
		plural: 'Wildläufer-Wandler',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gestaltwandler,Wandler,Wildläufer-Wandler',
	},
	{
		singular: 'Yuan-Ti',
		plural: 'Yuan-Ti',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Yuan-Ti',
	},
	{
		singular: 'Zentaur',
		plural: 'Zentauren',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Zentauren',
	},
];
