const raceArray = [
	{
		nounSingular: 'Aarakocra',
		nounPlural: 'Aarakocra',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Aarakocra',
	},
	{
		nounSingular: 'Aasimar',
		nounPlural: 'Aasimar',
		adjective: 'gefallene',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Aasimar',
	},
	{
		nounSingular: 'Astralelf',
		nounPlural: 'Astralelfen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Astralelfen',
	},
	{
		nounSingular: 'Autognom',
		nounPlural: 'Autognome',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Konstrukt,Autognome',
	},
	{
		nounSingular: 'Beschützer-Aasimar',
		nounPlural: 'Beschützer-Aasimar',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Beschützer-Aasimar',
	},
	{
		nounSingular: 'Blasself',
		nounPlural: 'Blasselfen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Blasselfen',
	},
	{
		nounSingular: 'Bullywug',
		nounPlural: 'Bullywugs',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Bullywug',
	},
	{
		nounSingular: 'Dämmerungself',
		nounPlural: 'Dämmerungselfen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Dämmerungselfen',
	},
	{
		nounSingular: 'Derro',
		nounPlural: 'Derro',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Derro',
	},
	{
		nounSingular: 'Dhampir',
		nounPlural: 'Dhampire',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Dhampire',
	},
	{
		nounSingular: 'Drachenblütige',
		nounPlural: 'Drachenblütige',
		adjective: 'chromatische',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Drachenblütige,Chromatische Drachenblütige',
	},
	{
		nounSingular: 'Drachenblütige',
		nounPlural: 'Drachenblütige',
		adjective: 'drachlingsblütige',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Drachenblütige,Drachlingsblütige Drachenblütige',
	},
	{
		nounSingular: 'Drachenblütige',
		nounPlural: 'Drachenblütige',
		adjective: 'metallische',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Drachenblütige,Metallische Drachenblütige',
	},
	{
		nounSingular: 'Dunkelelf',
		nounPlural: 'Dunkelelfen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Dunkelelfen',
	},
	{
		nounSingular: 'Dunkelzwerg',
		nounPlural: 'Dunkelzwerge',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Zwerge,Dunkelzwerge',
	},
	{
		nounSingular: 'Echsenmensch',
		nounPlural: 'Echsenmenschen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Echsenmenschen',
	},
	{
		nounSingular: 'Edelstein-Drachenblütige',
		nounPlural: 'Edelstein-Drachenblütige',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Drachenblütige,Edelstein-Drachenblütige',
	},
	{
		nounSingular: 'Eladrin',
		nounPlural: 'Eladrin',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Eladrin',
	},
	{
		nounSingular: 'Erd-Genasi',
		nounPlural: 'Erd-Genasi',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Genasi,Erd-Genasi',
	},
	{
		nounSingular: 'Fee',
		nounPlural: 'Feen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Feenwesen,Feen',
	},
	{
		nounSingular: 'Felsengnom',
		nounPlural: 'Felsengnome',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gnome,Felsengnome',
	},
	{
		nounSingular: 'Feuer-Genasi',
		nounPlural: 'Feuer-Genasi',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Genasi,Feuer-Genasi',
	},
	{
		nounSingular: 'Feuermolch',
		nounPlural: 'Feuermolche',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Feuermolche',
	},
	{
		nounSingular: 'Firbolg',
		nounPlural: 'Firbolgs',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Firbolg',
	},
	{
		nounSingular: 'Flinkläufer-Wandler',
		nounPlural: 'Flinkläufer-Wandler',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gestaltwandler,Wandler,Flinkläufer-Wandler',
	},
	{
		nounSingular: 'Gebirgzwerg',
		nounPlural: 'Gebirgzwerge',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Zwerge,Gebirgzwerge',
	},
	{
		nounSingular: 'Geißel-Aasimar',
		nounPlural: 'Geißel-Aasimar',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Aasimar,Geißel-Aasimar',
	},
	{
		nounSingular: 'Geisterwaisen-Halbling',
		nounPlural: 'Geisterwaisen-Halblinge',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Halblinge,Geisterwaisen-Halblinge',
	},
	{
		nounSingular: 'Giff',
		nounPlural: 'Giff',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Giff',
	},
	{
		nounSingular: 'Githyanki',
		nounPlural: 'Githyanki',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Githyanki',
	},
	{
		nounSingular: 'Githzerai',
		nounPlural: 'Githzerai',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Githzerai',
	},
	{
		nounSingular: 'Gnoll',
		nounPlural: 'Gnolle',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gnolle',
	},
	{
		nounSingular: 'Goblin',
		nounPlural: 'Goblins',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Goblinoide,Goblins',
	},
	{
		nounSingular: 'Goliath',
		nounPlural: 'Goliaths',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Goliaths',
	},
	{
		nounSingular: 'Grimlock',
		nounPlural: 'Grimlocks',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Grimlocks',
	},
	{
		nounSingular: 'Grottenschrat',
		nounPlural: 'Grottenschrate',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Goblinoide,Grottenschrate',
	},
	{
		nounSingular: 'Grung',
		nounPlural: 'Grungs',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Grung',
	},
	{
		nounSingular: 'Hadozee',
		nounPlural: 'Hadozee',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Hadozee',
	},
	{
		nounSingular: 'Halbdrache',
		nounPlural: 'Halbdrachen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Halbdrachen',
	},
	{
		nounSingular: 'Halbelf',
		nounPlural: 'Halbelfen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Halbelfen',
	},
	{
		nounSingular: 'Halbling',
		nounPlural: 'Halblinge',
		adjective: 'stämmige',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Halblinge,stämmige Halblinge',
	},
	{
		nounSingular: 'Halbork',
		nounPlural: 'Halborks',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Orks,Halborks',
	},
	{
		nounSingular: 'Harengon',
		nounPlural: 'Harengon',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Harengon',
	},
	{
		nounSingular: 'Hexenblütige',
		nounPlural: 'Hexenblütige',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Feenwesen,Hexenblütige',
	},
	{
		nounSingular: 'Hobgoblin',
		nounPlural: 'Hobgoblins',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Goblinoide,Hobgoblins',
	},
	{
		nounSingular: 'Hochelf',
		nounPlural: 'Hochelfen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Hochelfen',
	},
	{
		nounSingular: 'Hügelzwerg',
		nounPlural: 'Hügelzwerge',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Zwerge,Hügelzwerge',
	},
	{
		nounSingular: 'Kalashtar',
		nounPlural: 'Kalashtar',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kalashtar',
	},
	{
		nounSingular: 'Kender',
		nounPlural: 'Kender',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kender',
	},
	{
		nounSingular: 'Kenku',
		nounPlural: 'Kenkus',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kenkus',
	},
	{
		nounSingular: 'Kobold',
		nounPlural: 'Kobolde',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kobolde',
	},
	{
		nounSingular: 'Kraul',
		nounPlural: 'Kraul',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kraul',
	},
	{
		nounSingular: 'Kriegsgeschmiedete',
		nounPlural: 'Kriegsgeschmiedete',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kriegsgeschmiedete',
	},
	{
		nounSingular: 'Kuo-Toa',
		nounPlural: 'Kuo-Toas',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Kuo-Toas',
	},
	{
		nounSingular: 'Langzahn-Wandler',
		nounPlural: 'Langzahn-Wandler',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gestaltwandler,Wandler,Langzahn-Wandler',
	},
	{
		nounSingular: 'Lavakind',
		nounPlural: 'Lavakinder',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Lavakinder',
	},
	{
		nounSingular: 'Leichtfuß-Halbling',
		nounPlural: 'Leichtfuß-Halblinge',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Halblinge,Leichtfuß-Halblinge',
	},
	{
		nounSingular: 'Leonide',
		nounPlural: 'Leoniden',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Leoniden',
	},
	{
		nounSingular: 'Locathah',
		nounPlural: 'Locathah',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Locathah',
	},
	{
		nounSingular: 'Lotusden-Halbling',
		nounPlural: 'Lotusden-Halblinge',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Halblinge,Lotusden-Halblinge',
	},
	{
		nounSingular: 'Loxodon',
		nounPlural: 'Loxodon',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Loxodon',
	},
	{
		nounSingular: 'Luft-Genasi',
		nounPlural: 'Luft-Genasi',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Genasi,Luft-Genasi',
	},
	{
		nounSingular: 'Lykanthrop',
		nounPlural: 'Lykanthropen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gestaltwandler,Lykanthropen',
	},
	{
		nounSingular: 'Mazer',
		nounPlural: 'Mazer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Mazer',
	},
	{
		nounSingular: 'Meereself',
		nounPlural: 'Meereselfen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Meereselfen',
	},
	{
		nounSingular: 'Meervolk',
		nounPlural: 'Meervölker',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Meervölker',
	},
	{
		nounSingular: 'Mensch',
		nounPlural: 'Menschen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Menschen',
	},
	{
		nounSingular: 'Minotaur',
		nounPlural: 'Minotauren',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Minotauren',
	},
	{
		nounSingular: 'Mischlingsvolk',
		nounPlural: 'Mischlingsvölker',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Mischlingsvölker',
	},
	{
		nounSingular: 'Nagpa',
		nounPlural: 'Nagpas',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Nagpa',
	},
	{
		nounSingular: 'Nilbog',
		nounPlural: 'Nilbogs',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Nilbogs',
	},
	{
		nounSingular: 'Ork',
		nounPlural: 'Orks',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Orks',
	},
	{
		nounSingular: 'Orog',
		nounPlural: 'Orogs',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Orog',
	},
	{
		nounSingular: 'Plasmoide',
		nounPlural: 'Plasmoiden',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Schlicke,Plasmoiden',
	},
	{
		nounSingular: 'Quaggoth',
		nounPlural: 'Quaggoths',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Quaggoth',
	},
	{
		nounSingular: 'Ravenit-Drachenblütige',
		nounPlural: 'Ravenit-Drachenblütige',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Drachenblütige,Ravenit-Drachenblütige',
	},
	{
		nounSingular: 'Sahuagin',
		nounPlural: 'Sahuagin',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Sahuagin',
	},
	{
		nounSingular: 'Satyr',
		nounPlural: 'Satyren',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Feenwesen,Satyren',
	},
	{
		nounSingular: 'Saurianer',
		nounPlural: 'Saurianer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Saurianer',
	},
	{
		nounSingular: 'Shadar-Kai',
		nounPlural: 'Shadar-Kai',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Shadar-Kai',
	},
	{
		nounSingular: 'Simic-Hybride',
		nounPlural: 'Simic-Hybriden',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Simic-Hybriden',
	},
	{
		nounSingular: 'Tabaxi',
		nounPlural: 'Tabaxi',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Tabaxi',
	},
	{
		nounSingular: 'Thri-Kreen',
		nounPlural: 'Thri-Kreen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Thri-Kreen',
	},
	{
		nounSingular: 'Tiefengnom',
		nounPlural: 'Tiefengnome',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gnome,Tiefengnome',
	},
	{
		nounSingular: 'Tiefling',
		nounPlural: 'Tieflinge',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Tieflinge',
	},
	{
		nounSingular: 'Tierhaut-Wandler',
		nounPlural: 'Tierhaut-Wandler',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gestaltwandler,Wandler,Tierhaut-Wandler',
	},
	{
		nounSingular: 'Tortel',
		nounPlural: 'Tortel',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Tortel',
	},
	{
		nounSingular: 'Triton',
		nounPlural: 'Tritonen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Triton',
	},
	{
		nounSingular: 'Troglodyt',
		nounPlural: 'Troglodyten',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Troglodyten',
	},
	{
		nounSingular: 'Uhle',
		nounPlural: 'Uhlen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Uhlen',
	},
	{
		nounSingular: 'Vedalken',
		nounPlural: 'Vedalken',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Vedalken',
	},
	{
		nounSingular: 'Verdan',
		nounPlural: 'Verdan',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Goblinoide,Verdan',
	},
	{
		nounSingular: 'Waldelf',
		nounPlural: 'Waldelfen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Elfen,Waldelfen',
	},
	{
		nounSingular: 'Waldgnom',
		nounPlural: 'Waldgnome',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gnome,Waldgnome',
	},
	{
		nounSingular: 'Wasser-Genasi',
		nounPlural: 'Wasser-Genasi',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Genasi,Wasser-Genasi',
	},
	{
		nounSingular: 'Wechselbalg',
		nounPlural: 'Wechselbälger',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gestaltwandler,Wechselbälger',
	},
	{
		nounSingular: 'Wiedergeborene',
		nounPlural: 'Wiedergeborene',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Wiedergeborene',
	},
	{
		nounSingular: 'Wildläufer-Wandler',
		nounPlural: 'Wildläufer-Wandler',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Gestaltwandler,Wandler,Wildläufer-Wandler',
	},
	{
		nounSingular: 'Yuan-Ti',
		nounPlural: 'Yuan-Ti',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'eigenname',
		declinationPattern: 'eigenname',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Yuan-Ti',
	},
	{
		nounSingular: 'Zentaur',
		nounPlural: 'Zentauren',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Humanoide,Zentauren',
	},
];
