const religiousArray = [
	{
		singular: 'Bekehrung',
		plural: 'Bekehrungen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Bekehrungen',
	},
	{
		singular: 'Heilige',
		plural: 'Heilige',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Heilige',
	},
	{
		singular: 'Ideologie',
		plural: 'Ideologien',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Ideologien',
	},
	{
		singular: 'Ikone',
		plural: 'Ikonen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Ikonen',
	},
	{
		singular: 'Intervention',
		plural: 'Interventionen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Interventionen',
	},
	{
		singular: 'Wunder',
		plural: 'Wunder',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Wunder',
	},
	{
		singular: 'Pantheon',
		plural: 'Pantheons',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Pantheons',
	},
	{
		singular: 'Sünde',
		plural: 'Sünden',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Sünden',
	},
	{
		singular: 'Geist',
		plural: 'Geister',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Geister',
	},
	{
		singular: 'Seele',
		plural: 'Seelen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Seelen',
	},
	{
		singular: 'Symbol',
		plural: 'Symbole',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Symbole',
	},
	{
		singular: 'Tabu',
		plural: 'Tabus',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Tabus',
	},
	{
		singular: 'Abgesandte',
		plural: 'Abgesandte',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Abgesandte',
	},
	{
		singular: 'Absolution',
		plural: 'Absolutionen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Absolutionen',
	},
	{
		singular: 'Apostel',
		plural: 'Apostel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Apostel',
	},
	{
		singular: 'Gebet',
		plural: 'Gebete',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Gebete',
	},
	{
		singular: 'Gebot',
		plural: 'Gebote',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Gebote',
	},
	{
		singular: 'Heiligtum',
		plural: 'Heiligtümer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Heiligtümer',
	},
	{
		singular: 'Ritual',
		plural: 'Rituale',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Rituale',
	},
	{
		singular: 'Prophet',
		plural: 'Propheten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Propheten',
	},
];
