const religiousArray = [
	{
		nounSingular: 'Bekehrung',
		nounPlural: 'Bekehrungen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Bekehrungen',
	},
	{
		nounSingular: 'Heilige',
		nounPlural: 'Heilige',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Heilige',
	},
	{
		nounSingular: 'Ideologie',
		nounPlural: 'Ideologien',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Ideologien',
	},
	{
		nounSingular: 'Ikone',
		nounPlural: 'Ikonen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Ikonen',
	},
	{
		nounSingular: 'Intervention',
		nounPlural: 'Interventionen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Interventionen',
	},
	{
		nounSingular: 'Wunder',
		nounPlural: 'Wunder',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Wunder',
	},
	{
		nounSingular: 'Pantheon',
		nounPlural: 'Pantheons',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Pantheons',
	},
	{
		nounSingular: 'Sünde',
		nounPlural: 'Sünden',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Sünden',
	},
	{
		nounSingular: 'Geist',
		nounPlural: 'Geister',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Geister',
	},
	{
		nounSingular: 'Seele',
		nounPlural: 'Seelen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Seelen',
	},
	{
		nounSingular: 'Symbol',
		nounPlural: 'Symbole',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Symbole',
	},
	{
		nounSingular: 'Tabu',
		nounPlural: 'Tabus',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Tabus',
	},
	{
		nounSingular: 'Abgesandte',
		nounPlural: 'Abgesandte',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'substantiviertesAdjektiv',
		declinationPattern: 'substantiviertesAdjektiv',
		campaignSetting: 'Universal',
		tags: 'Abgesandte',
	},
	{
		nounSingular: 'Absolution',
		nounPlural: 'Absolutionen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Absolutionen',
	},
	{
		nounSingular: 'Apostel',
		nounPlural: 'Apostel',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Apostel',
	},
	{
		nounSingular: 'Gebet',
		nounPlural: 'Gebete',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Gebete',
	},
	{
		nounSingular: 'Gebot',
		nounPlural: 'Gebote',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Gebote',
	},
	{
		nounSingular: 'Heiligtum',
		nounPlural: 'Heiligtümer',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Heiligtümer',
	},
	{
		nounSingular: 'Ritual',
		nounPlural: 'Rituale',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Rituale',
	},
	{
		nounSingular: 'Prophet',
		nounPlural: 'Propheten',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W1',
		campaignSetting: 'Universal',
		tags: 'Propheten',
	},
];
