const terrainArray = [
	{
		singular: 'Schlucht',
		plural: 'Schluchten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Schluchten',
	},
	{
		singular: 'Höhle',
		plural: 'Höhlen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Höhlen',
	},
	{
		singular: 'Wüste',
		plural: 'Wüsten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Wüsten',
	},
	{
		singular: 'Wald',
		plural: 'Wälder',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Wälder',
	},
	{
		singular: 'Gletscher',
		plural: 'Gletscher',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Gletscher',
	},
	{
		singular: 'Hügel',
		plural: 'Hügel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Hügel',
	},
	{
		singular: 'Unterreich',
		plural: 'Unterreiche',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Unterreiche',
	},
	{
		singular: 'Dschungel',
		plural: 'Dschungel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Dschungel',
	},
	{
		singular: 'See',
		plural: 'Seen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'gemischteDeklination',
		declinationPattern: 'W3',
		campaignSetting: 'Universal',
		tags: 'Seen',
	},
	{
		singular: 'Tafelberg',
		plural: 'Tafelberge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Tafelberge',
	},
	{
		singular: 'Berg',
		plural: 'Berge',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Berge',
	},
	{
		singular: 'Meer',
		plural: 'Meere',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Meere',
	},
	{
		singular: 'Steppe',
		plural: 'Steppen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Steppen',
	},
	{
		singular: 'Fluss',
		plural: 'Flüsse',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Flüsse',
	},
	{
		singular: 'Salzwüste',
		plural: 'Salzwüsten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Salzwüsten',
	},
	{
		singular: 'Savanne',
		plural: 'Savannen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Savannen',
	},
	{
		singular: 'Sumpf',
		plural: 'Sümpfe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Sümpfe',
	},
	{
		singular: 'Tundra',
		plural: 'Tundren',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Tundren',
	},
	{
		singular: 'Vulkan',
		plural: 'Vulkane',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Vulkane',
	},
	{
		singular: 'Ödland',
		plural: 'Ödländer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Ödländer',
	},
];
