const terrainArray = [
	{
		nounSingular: 'Schlucht',
		nounPlural: 'Schluchten',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Schluchten',
	},
	{
		nounSingular: 'Höhle',
		nounPlural: 'Höhlen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Höhlen',
	},
	{
		nounSingular: 'Wüste',
		nounPlural: 'Wüsten',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Wüsten',
	},
	{
		nounSingular: 'Wald',
		nounPlural: 'Wälder',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Wälder',
	},
	{
		nounSingular: 'Gletscher',
		nounPlural: 'Gletscher',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Gletscher',
	},
	{
		nounSingular: 'Hügel',
		nounPlural: 'Hügel',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Hügel',
	},
	{
		nounSingular: 'Unterreich',
		nounPlural: 'Unterreiche',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Unterreiche',
	},
	{
		nounSingular: 'Dschungel',
		nounPlural: 'Dschungel',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Dschungel',
	},
	{
		nounSingular: 'See',
		nounPlural: 'Seen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'gemischteDeklination',
		declinationPattern: 'W3',
		campaignSetting: 'Universal',
		tags: 'Seen',
	},
	{
		nounSingular: 'Tafelberg',
		nounPlural: 'Tafelberge',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Tafelberge',
	},
	{
		nounSingular: 'Berg',
		nounPlural: 'Berge',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Berge',
	},
	{
		nounSingular: 'Meer',
		nounPlural: 'Meere',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Meere',
	},
	{
		nounSingular: 'Steppe',
		nounPlural: 'Steppen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Steppen',
	},
	{
		nounSingular: 'Fluss',
		nounPlural: 'Flüsse',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Flüsse',
	},
	{
		nounSingular: 'Salzwüste',
		nounPlural: 'Salzwüsten',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Salzwüsten',
	},
	{
		nounSingular: 'Savanne',
		nounPlural: 'Savannen',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Savannen',
	},
	{
		nounSingular: 'Sumpf',
		nounPlural: 'Sümpfe',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Sümpfe',
	},
	{
		nounSingular: 'Tundra',
		nounPlural: 'Tundren',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Tundren',
	},
	{
		nounSingular: 'Vulkan',
		nounPlural: 'Vulkane',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Vulkane',
	},
	{
		nounSingular: 'Ödland',
		nounPlural: 'Ödländer',
		adjective: '',
		prefix: '',
		suffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Ödländer',
	},
];
