const weaponArray = [
	{
		nounSingular: 'Anderthalbhänder',
		nounPlural: 'Anderthalbhänder',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Anderthalbhänder',
	},
	{
		nounSingular: 'Beil',
		nounPlural: 'Beile',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Wurfwaffen,Beile',
	},
	{
		nounSingular: 'Blasrohr',
		nounPlural: 'Blasrohre',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Blasrohre',
	},
	{
		nounSingular: 'Boomerang',
		nounPlural: 'Boomerangs',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Wurfwaffen,Boomerangs',
	},
	{
		nounSingular: 'Dolch',
		nounPlural: 'Dolche',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Wurfwaffen,Dolche',
	},
	{
		nounSingular: 'Dreizack',
		nounPlural: 'Dreizacke',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Dreizacke',
	},
	{
		nounSingular: 'Flegel',
		nounPlural: 'Flegel',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Flegel',
	},
	{
		nounSingular: 'Gleve',
		nounPlural: 'Gleven',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Gleven',
	},
	{
		nounSingular: 'Kurzspeer',
		nounPlural: 'Kurzspeere',
		nounAdjective: 'hakenförmige',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Hakenförmige Kurzspeere',
	},
	{
		nounSingular: 'Handarbrust',
		nounPlural: 'Handarmbrüste',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S3',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Handarmbrüste',
	},
	{
		nounSingular: 'Hellebarde',
		nounPlural: 'Hellebarden',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Hellebarden',
	},
	{
		nounSingular: 'Hoopak',
		nounPlural: 'Hoopaks',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Hoopaks',
	},
	{
		nounSingular: 'Waffe',
		nounPlural: 'Waffen',
		nounAdjective: 'improvisierte',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Improvisierte Waffen',
	},
	{
		nounSingular: 'Kampfstab',
		nounPlural: 'Kampfstäbe',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Kampfstäbe',
	},
	{
		nounSingular: 'Knüppel',
		nounPlural: 'Knüppel',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Knüppel',
	},
	{
		nounSingular: 'Kriegshacke',
		nounPlural: 'Kriegshacken',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Kriegshacken',
	},
	{
		nounSingular: 'Kriegshammer',
		nounPlural: 'Kriegshämmer',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S5',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Kriegshämmer',
	},
	{
		nounSingular: 'Krummsäbel',
		nounPlural: 'Krummsäbel',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Krummsäbel',
	},
	{
		nounSingular: 'Kurzbogen',
		nounPlural: 'Kurzbogen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Kurzbogen',
	},
	{
		nounSingular: 'Kurzschwert',
		nounPlural: 'Kurzschwerter',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Kurzschwerter',
	},
	{
		nounSingular: 'Langbogen',
		nounPlural: 'Langbogen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Langbogen',
	},
	{
		nounSingular: 'Langschwert',
		nounPlural: 'Langschwerter',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Langschwerter',
	},
	{
		nounSingular: 'Lanze',
		nounPlural: 'Lanzen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Lanzen',
	},
	{
		nounSingular: 'Armbrust',
		nounPlural: 'Armbrüste',
		nounAdjective: 'leichte',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S3',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Leichte Armbrüste',
	},
	{
		nounSingular: 'Repetierarmbrust',
		nounPlural: 'Repetierarmbrüste',
		nounAdjective: 'leichte',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S3',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Leichte Repetierarmbrüste',
	},
	{
		nounSingular: 'Hammer',
		nounPlural: 'Hämmer',
		nounAdjective: 'leichte',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S5',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Leichte Hämmer',
	},
	{
		nounSingular: 'Morgenstern',
		nounPlural: 'Morgensterne',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Morgensterne',
	},
	{
		nounSingular: 'Netz',
		nounPlural: 'Netze',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Wurfwaffen,Netze',
	},
	{
		nounSingular: 'Peitsche',
		nounPlural: 'Peitschen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Peitschen',
	},
	{
		nounSingular: 'Pike',
		nounPlural: 'Piken',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Piken',
	},
	{
		nounSingular: 'Rapier',
		nounPlural: 'Rapiere',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'gemischteDeklination',
		declinationPattern: 'W3',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Rapiere',
	},
	{
		nounSingular: 'Schlagring',
		nounPlural: 'Schlagringe',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Schlagringe',
	},
	{
		nounSingular: 'Schleuder',
		nounPlural: 'Schleudern',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Schleudern',
	},
	{
		nounSingular: 'Armbrust',
		nounPlural: 'Armbrüste',
		nounAdjective: 'schwere',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S3',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Armbrüste',
	},
	{
		nounSingular: 'Sense',
		nounPlural: 'Sensen',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Sensen',
	},
	{
		nounSingular: 'Sichel',
		nounPlural: 'Sicheln',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Sicheln',
	},
	{
		nounSingular: 'Speer',
		nounPlural: 'Speere',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Wurfwaffen,Speere',
	},
	{
		nounSingular: 'Stachelkette',
		nounPlural: 'Stachelketten',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Stachelketten',
	},
	{
		nounSingular: 'Streitaxt',
		nounPlural: 'Streitäxte',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S3',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Streitäxte',
	},
	{
		nounSingular: 'Streitkolben',
		nounPlural: 'Streitkolben',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Streitkolben',
	},
	{
		nounSingular: 'Tonfa',
		nounPlural: 'Tonfas',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Tonfas',
	},
	{
		nounSingular: 'Langbogen',
		nounPlural: 'Langbögen',
		nounAdjective: 'übergroße',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S5',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Übergroße Langbögen',
	},
	{
		nounSingular: 'Wurfpfeil',
		nounPlural: 'Wurfpfeile',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Wurfwaffen,Wurfpfeile',
	},
	{
		nounSingular: 'Wurfspeer',
		nounPlural: 'Wurfspeere',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Wurfwaffen,Wurfspeere',
	},
	{
		nounSingular: 'Ylkwa',
		nounPlural: 'Ylkwas',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Ylkwas',
	},
	{
		nounSingular: 'Zweihandaxt',
		nounPlural: 'Zweihandäxte',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'femininum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S3',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Zweihandäxte',
	},
	{
		nounSingular: 'Zweihandhammer',
		nounPlural: 'Zweihandhämmer',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S5',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Zweihandhämmer',
	},
	{
		nounSingular: 'Zweihandknüppel',
		nounPlural: 'Zweihandknüppel',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Zweihandknüppel',
	},
	{
		nounSingular: 'Zweihandschwert',
		nounPlural: 'Zweihandschwerter',
		nounAdjective: '',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Zweihandschwerter',
	},
	{
		nounSingular: 'Krummsäbel',
		nounPlural: 'Krummsäbel',
		nounAdjective: 'zweiklingige',
		nounPrefix: '',
		nounSuffix: '',
		nounGender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Zweiklingige Krummsäbel',
	},
];
