const weaponArray = [
	{
		singular: 'Anderthalbhänder',
		plural: 'Anderthalbhänder',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Anderthalbhänder',
	},
	{
		singular: 'Beil',
		plural: 'Beile',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Wurfwaffen,Beile',
	},
	{
		singular: 'Blasrohr',
		plural: 'Blasrohre',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Blasrohre',
	},
	{
		singular: 'Boomerang',
		plural: 'Boomerangs',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Wurfwaffen,Boomerangs',
	},
	{
		singular: 'Dolch',
		plural: 'Dolche',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Wurfwaffen,Dolche',
	},
	{
		singular: 'Dreizack',
		plural: 'Dreizacke',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Dreizacke',
	},
	{
		singular: 'Flegel',
		plural: 'Flegel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Flegel',
	},
	{
		singular: 'Gleve',
		plural: 'Gleven',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Gleven',
	},
	{
		singular: 'Kurzspeer',
		plural: 'Kurzspeere',
		adjective: 'hakenförmige',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Hakenförmige Kurzspeere',
	},
	{
		singular: 'Handarbrust',
		plural: 'Handarmbrüste',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S3',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Handarmbrüste',
	},
	{
		singular: 'Hellebarde',
		plural: 'Hellebarden',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Hellebarden',
	},
	{
		singular: 'Hoopak',
		plural: 'Hoopaks',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Hoopaks',
	},
	{
		singular: 'Waffe',
		plural: 'Waffen',
		adjective: 'improvisierte',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Improvisierte Waffen',
	},
	{
		singular: 'Kampfstab',
		plural: 'Kampfstäbe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S1',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Kampfstäbe',
	},
	{
		singular: 'Knüppel',
		plural: 'Knüppel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Knüppel',
	},
	{
		singular: 'Kriegshacke',
		plural: 'Kriegshacken',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Kriegshacken',
	},
	{
		singular: 'Kriegshammer',
		plural: 'Kriegshämmer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S5',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Kriegshämmer',
	},
	{
		singular: 'Krummsäbel',
		plural: 'Krummsäbel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Krummsäbel',
	},
	{
		singular: 'Kurzbogen',
		plural: 'Kurzbogen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Kurzbogen',
	},
	{
		singular: 'Kurzschwert',
		plural: 'Kurzschwerter',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Kurzschwerter',
	},
	{
		singular: 'Langbogen',
		plural: 'Langbogen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Langbogen',
	},
	{
		singular: 'Langschwert',
		plural: 'Langschwerter',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Langschwerter',
	},
	{
		singular: 'Lanze',
		plural: 'Lanzen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Lanzen',
	},
	{
		singular: 'Armbrust',
		plural: 'Armbrüste',
		adjective: 'leichte',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S3',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Leichte Armbrüste',
	},
	{
		singular: 'Repetierarmbrust',
		plural: 'Repetierarmbrüste',
		adjective: 'leichte',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S3',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Leichte Repetierarmbrüste',
	},
	{
		singular: 'Hammer',
		plural: 'Hämmer',
		adjective: 'leichte',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S5',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Leichte Hämmer',
	},
	{
		singular: 'Morgenstern',
		plural: 'Morgensterne',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Morgensterne',
	},
	{
		singular: 'Netz',
		plural: 'Netze',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Wurfwaffen,Netze',
	},
	{
		singular: 'Peitsche',
		plural: 'Peitschen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Peitschen',
	},
	{
		singular: 'Pike',
		plural: 'Piken',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Piken',
	},
	{
		singular: 'Rapier',
		plural: 'Rapiere',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'gemischteDeklination',
		declinationPattern: 'W3',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Rapiere',
	},
	{
		singular: 'Schlagring',
		plural: 'Schlagringe',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Schlagringe',
	},
	{
		singular: 'Schleuder',
		plural: 'Schleudern',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Schleudern',
	},
	{
		singular: 'Armbrust',
		plural: 'Armbrüste',
		adjective: 'schwere',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S3',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Armbrüste',
	},
	{
		singular: 'Sense',
		plural: 'Sensen',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Sensen',
	},
	{
		singular: 'Sichel',
		plural: 'Sicheln',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Sicheln',
	},
	{
		singular: 'Speer',
		plural: 'Speere',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Wurfwaffen,Speere',
	},
	{
		singular: 'Stachelkette',
		plural: 'Stachelketten',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'schwacheDeklination',
		declinationPattern: 'W2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Stachelketten',
	},
	{
		singular: 'Streitaxt',
		plural: 'Streitäxte',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S3',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Streitäxte',
	},
	{
		singular: 'Streitkolben',
		plural: 'Streitkolben',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Streitkolben',
	},
	{
		singular: 'Tonfa',
		plural: 'Tonfas',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Tonfas',
	},
	{
		singular: 'Langbogen',
		plural: 'Langbögen',
		adjective: 'übergroße',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S5',
		campaignSetting: 'Universal',
		tags: 'Fernkampfwaffen,Übergroße Langbögen',
	},
	{
		singular: 'Wurfpfeil',
		plural: 'Wurfpfeile',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Wurfwaffen,Wurfpfeile',
	},
	{
		singular: 'Wurfspeer',
		plural: 'Wurfspeere',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S4',
		campaignSetting: 'Universal',
		tags: 'Wurfwaffen,Wurfspeere',
	},
	{
		singular: 'Ylkwa',
		plural: 'Ylkwas',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'fremdWort',
		declinationPattern: 'fremdWort',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Ylkwas',
	},
	{
		singular: 'Zweihandaxt',
		plural: 'Zweihandäxte',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'femininum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S3',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Zweihandäxte',
	},
	{
		singular: 'Zweihandhammer',
		plural: 'Zweihandhämmer',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S5',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Zweihandhämmer',
	},
	{
		singular: 'Zweihandknüppel',
		plural: 'Zweihandknüppel',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Zweihandknüppel',
	},
	{
		singular: 'Zweihandschwert',
		plural: 'Zweihandschwerter',
		adjective: '',
		prefix: '',
		suffix: '',
		gender: 'neutrum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S2',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Zweihandschwerter',
	},
	{
		singular: 'Krummsäbel',
		plural: 'Krummsäbel',
		adjective: 'zweiklingige',
		prefix: '',
		suffix: '',
		gender: 'maskulinum',
		declinationRule: 'starkeDeklination',
		declinationPattern: 'S6',
		campaignSetting: 'Universal',
		tags: 'Nahkampfwaffen,Zweiklingige Krummsäbel',
	},
];
