const nounMapping = [
	{english: 'randomClass', german: 'Klasse', array: 'classArray'},
	{english: 'randomClass2', german: 'Klasse2', array: 'classArray'},
	{english: 'randomClass3', german: 'Klasse3', array: 'classArray'},
	{english: 'randomRace', german: 'Volk', array: 'raceArray'},
	{english: 'randomRace2', german: 'Volk2', array: 'raceArray'},
	{english: 'randomRace3', german: 'Volk3', array: 'raceArray'},
	{english: 'randomCreatureType', german: 'Kreaturtyp', array: 'creatureTypeArray'},
	{english: 'randomCreatureType2', german: 'Kreaturtyp2', array: 'creatureTypeArray'},
	{english: 'randomCreatureType2', german: 'Kreaturtyp2', array: 'creatureTypeArray'},
	{english: 'randomProfession', german: 'Beruf', array: 'professionArray'},
	{english: 'randomProfession2', german: 'Beruf2', array: 'professionArray'},
	{english: 'randomProfession3', german: 'Beruf3', array: 'professionArray'},
	{
		english: 'randomAdventuringGear',
		german: 'Abenteuerausrüstung',
		array: 'adventuringGearArray',
	},
	{
		english: 'randomAdventuringGear2',
		german: 'Abenteuerausrüstung2',
		array: 'adventuringGearArray',
	},
	{
		english: 'randomAdventuringGear3',
		german: 'Abenteuerausrüstung3',
		array: 'adventuringGearArray',
	},
	{english: 'randomArmour', german: 'Rüstung', array: 'armourArray'},
	{english: 'randomArmour2', german: 'Rüstung2', array: 'armourArray'},
	{english: 'randomArmour3', german: 'Rüstung3', array: 'armourArray'},
	{english: 'randomBuilding', german: 'Gebäude', array: 'buildingArray'},
	{english: 'randomBuilding2', german: 'Gebäude2', array: 'buildingArray'},
	{english: 'randomBuilding3', german: 'Gebäude3', array: 'buildingArray'},
	{english: 'randomAnimal', german: 'Tier', array: 'animalArray'},
	{english: 'randomAnimal2', german: 'Tier2', array: 'animalArray'},
	{english: 'randomAnimal3', german: 'Tier3', array: 'animalArray'},
	{english: 'randomWeapon', german: 'Waffe', array: 'weaponArray'},
	{english: 'randomWeapon2', german: 'Waffe2', array: 'weaponArray'},
	{english: 'randomWeapon2', german: 'Waffe2', array: 'weaponArray'},
	{english: 'randomEvent', german: 'Ereignis', array: 'eventArray'},
	{english: 'randomEvent2', german: 'Ereignis2', array: 'eventArray'},
	{english: 'randomEvent3', german: 'Ereignis3', array: 'eventArray'},
	{english: 'randomMetal', german: 'Metall', array: 'metalArray'},
	{english: 'randomMetal2', german: 'Metall2', array: 'metalArray'},
	{english: 'randomMetal3', german: 'Metall3', array: 'metalArray'},
	{english: 'randomTerrain', german: 'Terrain', array: 'terrainArray'},
	{english: 'randomTerrain2', german: 'Terrain2', array: 'terrainArray'},
	{english: 'randomTerrain3', german: 'Terrain3', array: 'terrainArray'},
];
